# Web Scraping Assighnemt - 2

### Q1:   Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data. You have to scrape the data from webpage https://www.naukri.com/

In [1]:
# Importing necessary Libraries

import selenium
from selenium import webdriver
import pandas as pd

In [2]:
# Let's first connect to the driver

driver = webdriver.Chrome("chromedriver.exe")
print(driver)

<selenium.webdriver.chrome.webdriver.WebDriver (session="0aa73c6aa0fe10f5441547a6d5b55b3e")>

In [3]:
# Let's open the url https://www.naukri.com/

url = "https://www.naukri.com/"
driver.get(url)

In [4]:
# Writer on job title field

job_tag = driver.find_element_by_xpath('//input[@class="sugInp"]')
job_tag.send_keys("Data Analyst")

In [5]:
# Write on job location field

job_loc = driver.find_element_by_xpath('//input[@id="qsb-location-sugg"]')
job_loc.send_keys("Bangalore")

In [6]:
# Click on search button

search_click = driver.find_element_by_xpath('//button[@class="btn"]')
search_click.click()

In [7]:
# Empty Lists

job_title = []
job_location = []
company_name = []
experience_required = []

In [8]:
# Job title

title = driver.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]')

for i in title:
    job_title.append(i.text)
job_title

['Data Analyst',
 'Systems and Data Analyst, Safety and Provisioning',
 'Data Annotator | Data Entry | Work From Home | Data analyst | Data QC',
 'Senior CDP (Customer Data Platform) Analyst',
 'Senior Analyst - Data & Analytics',
 'Senior Data Analyst - SQL/Tableau/Redshift',
 'Lead Data Analyst',
 'Lead Data Analyst',
 'Data Analyst , Product',
 'Business Data Analyst - Alteryx/Hadoop',
 'Senior Data Analyst',
 'Senior Data Analyst',
 'Immediate Opening For Senior Data Analyst (PLSQ) For Pune location',
 'Data Analyst - Work from Home',
 'Data Analyst',
 'Data Analyst',
 'Medical Operations Data Analyst',
 'ID&A - Data Analyst - Informatica MDM',
 'Data analysts',
 'Data Analyst']

In [9]:
# Job Location

location = driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]')

for i in location:
    job_location.append(i.text)
job_location

['Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Noida, Mumbai, Indore, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru\n(WFH during Covid)',
 'United States (USA), Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Pune, Bangalore/Bengaluru',
 'Pune, Bangalore/Bengaluru, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru(Vyalikaval)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [10]:
# Company Name

company = driver.find_elements_by_xpath('//div[@class="mt-7 companyInfo subheading lh16"]')

for i in company:
    company_name.append(i.text)
company_name

['Enzen Global Solutions Pvt. Ltd\n4.3\n(116 Reviews)',
 'AECOM India Private Limited\n4.0\n(665 Reviews)',
 'saarthi.ai\n3.6\n(4 Reviews)',
 'Indegene\n3.8\n(287 Reviews)',
 'Indegene\n3.8\n(287 Reviews)',
 'Pronto Consulting Services',
 'Bidgely Technologies Private Limited\n4.6\n(5 Reviews)',
 'MediaMath',
 'MediaMath',
 'Talent Placers',
 'Publicis Groupe\n3.3\n(64 Reviews)',
 'Publicis Groupe\n3.3\n(64 Reviews)',
 'Harman Connected Services\n3.7\n(603 Reviews)',
 'POWER STORES E COMMERCE PRIVATE LIMITED',
 'Innovsource Services Private Limited\n4.2\n(650 Reviews)',
 'Enzen Global Solutions\n4.3\n(116 Reviews)',
 'Tricog Health India Private Limited\n4.4\n(10 Reviews)',
 'Shell India Markets Private Limited\n4.1\n(686 Reviews)',
 'IBM India Pvt. Limited\n4.0\n(10044 Reviews)',
 'Kwalee ltd.']

In [11]:
# Experience Required

experience = driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi experience"]')

for i in experience:
    experience_required.append(i.text)
experience_required

['6-8 Yrs',
 '3-5 Yrs',
 '0-2 Yrs',
 '4-9 Yrs',
 '3-8 Yrs',
 '6-10 Yrs',
 '5-10 Yrs',
 '8-13 Yrs',
 '4-9 Yrs',
 '5-8 Yrs',
 '1-3 Yrs',
 '1-5 Yrs',
 '3-6 Yrs',
 '2-5 Yrs',
 '1-6 Yrs',
 '3-7 Yrs',
 '3-6 Yrs',
 '6-9 Yrs',
 '5-10 Yrs',
 '2-7 Yrs']

In [12]:
First_10_Jobs_Data_Analyst = pd.DataFrame(index = list(range(1,11)))

First_10_Jobs_Data_Analyst["Job Title"] = job_title[:10]
First_10_Jobs_Data_Analyst["Company Name"] = company_name[:10]
First_10_Jobs_Data_Analyst["Experience Required"] = experience_required[:10]
First_10_Jobs_Data_Analyst["Job Location"] = job_location[:10]

First_10_Jobs_Data_Analyst

,Job Title,Company Name,Experience Required,Job Location
1,Data Analyst,Enzen Global Solutions Pvt. Ltd\n4.3\n(116 Rev...,6-8 Yrs,Bangalore/Bengaluru
2,"Systems and Data Analyst, Safety and Provisioning",AECOM India Private Limited\n4.0\n(665 Reviews),3-5 Yrs,Bangalore/Bengaluru
3,Data Annotator | Data Entry | Work From Home |...,saarthi.ai\n3.6\n(4 Reviews),0-2 Yrs,Bangalore/Bengaluru
4,Senior CDP (Customer Data Platform) Analyst,Indegene\n3.8\n(287 Reviews),4-9 Yrs,Bangalore/Bengaluru
5,Senior Analyst - Data & Analytics,Indegene\n3.8\n(287 Reviews),3-8 Yrs,Bangalore/Bengaluru
6,Senior Data Analyst - SQL/Tableau/Redshift,Pronto Consulting Services,6-10 Yrs,"Noida, Mumbai, Indore, Hyderabad/Secunderabad,..."
7,Lead Data Analyst,Bidgely Technologies Private Limited\n4.6\n(5 ...,5-10 Yrs,"United States (USA), Bangalore/Bengaluru"
8,Lead Data Analyst,MediaMath,8-13 Yrs,Bangalore/Bengaluru
9,"Data Analyst , Product",MediaMath,4-9 Yrs,Bangalore/Bengaluru
10,Business Data Analyst - Alteryx/Hadoop,Talent Placers,5-8 Yrs,Bangalore/Bengaluru

### Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, full job-description. You have to scrape first 10 jobs data. You have to scrape the data from webpage https://www.naukri.com/

To find the description of the job, we have to enter in the job, So let's find the job urls

In [13]:
# Importing necessary Libraries

import selenium
from selenium import webdriver
import pandas as pd

In [14]:
# Let's first connect to the driver

driver = webdriver.Chrome("chromedriver.exe")
print(driver)

<selenium.webdriver.chrome.webdriver.WebDriver (session="feab58f6fe0594ab0215433d09403b37")>

In [15]:
# Let's open the url https://www.naukri.com/

url = "https://www.naukri.com/"
driver.get(url)

In [16]:
# Writer on job title field

job_tag = driver.find_element_by_xpath('//input[@class="sugInp"]')
job_tag.send_keys("Data Scientist")

In [17]:
# Write on job location field

job_loc = driver.find_element_by_xpath('//input[@id="qsb-location-sugg"]')
job_loc.send_keys("Bangalore")

In [18]:
# Click on search button

search_click = driver.find_element_by_xpath('//button[@class="btn"]')
search_click.click()

In [19]:
# Empty Lists

url_pages = []
job_title = []
job_location = []
company_name = []
job_description = []

In [20]:
# finding url pages for job description

job_url = driver.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]')
for i in job_url:
    url_pages.append(i.get_attribute("href"))

url_pages

['https://www.naukri.com/job-listings-senior-data-scientist-publicis-groupe-bangalore-bengaluru-2-to-5-years-030821501259?src=jobsearchDesk&sid=1628018705683797&xp=1&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-bidgely-technologies-private-limited-bangalore-bengaluru-4-to-6-years-030821500043?src=jobsearchDesk&sid=1628018705683797&xp=2&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-goals-101-data-solutions-pvt-ltd-new-delhi-bangalore-bengaluru-delhi-ncr-4-to-8-years-030821000870?src=jobsearchDesk&sid=1628018705683797&xp=3&px=1',
 'https://www.naukri.com/job-listings-sr-data-scientist-tech-lead-data-science-confidential-bangalore-bengaluru-6-to-9-years-020821903704?src=jobsearchDesk&sid=1628018705683797&xp=4&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-randstad-india-pvt-ltd-bangalore-bengaluru-4-to-9-years-280721000424?src=jobsearchDesk&sid=1628018705683797&xp=5&px=1',
 'https://www.naukri.com/job-listings-data-engineers-data-scientist-and-sap-teamware-solutions-bangalore-bengaluru-7-to-10-years-300721500677?src=jobsearchDesk&sid=1628018705683797&xp=6&px=1',
 'https://www.naukri.com/job-listings-western-digital-data-scientist-3-western-digital-bangalore-bengaluru-4-to-5-years-030821500726?src=jobsearchDesk&sid=1628018705683797&xp=7&px=1',
 'https://www.naukri.com/job-listings-western-digital-data-scientist-western-digital-bangalore-bengaluru-10-to-12-years-030821500725?src=jobsearchDesk&sid=1628018705683797&xp=8&px=1',
 'https://www.naukri.com/job-listings-data-scientist-4-western-digital-bangalore-bengaluru-6-to-8-years-030821500721?src=jobsearchDesk&sid=1628018705683797&xp=9&px=1',
 'https://www.naukri.com/job-listings-data-scientist-hotelhub-bangalore-bengaluru-6-to-11-years-020821500146?src=jobsearchDesk&sid=1628018705683797&xp=10&px=1',
 'https://www.naukri.com/job-listings-data-scientist-4-western-digital-bangalore-bengaluru-5-to-6-years-020821500513?src=jobsearchDesk&sid=1628018705683797&xp=11&px=1',
 'https://www.naukri.com/job-listings-immediate-openings-for-data-scientist-with-6-to-7-yrs-of-experience-entune-it-consulting-private-limited-kolkata-hyderabad-secunderabad-pune-ahmedabad-chennai-bangalore-bengaluru-delhi-ncr-mumbai-all-areas-5-to-8-years-020821005914?src=jobsearchDesk&sid=1628018705683797&xp=12&px=1',
 'https://www.naukri.com/job-listings-data-scientist-sr-data-scientist-persolkelly-india-private-limited-bangalore-bengaluru-4-to-9-years-030821000159?src=jobsearchDesk&sid=1628018705683797&xp=13&px=1',
 'https://www.naukri.com/job-listings-senior-software-engineer-data-scientist-ara-resources-bangalore-bengaluru-6-to-10-years-290721906399?src=jobsearchDesk&sid=1628018705683797&xp=14&px=1',
 'https://www.naukri.com/job-listings-senior-associate-data-scientist-novotree-minds-consulting-pvt-limited-bangalore-bengaluru-4-to-7-years-300721001832?src=jobsearchDesk&sid=1628018705683797&xp=15&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-gojek-tech-bangalore-bengaluru-4-to-8-years-290721501291?src=jobsearchDesk&sid=1628018705683797&xp=16&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-go-jek-india-bangalore-bengaluru-6-to-12-years-290721501288?src=jobsearchDesk&sid=1628018705683797&xp=17&px=1',
 'https://www.naukri.com/job-listings-sr-data-scientist-fabhotel-aay-kay-model-town-bangalore-bengaluru-2-to-5-years-280721500564?src=jobsearchDesk&sid=1628018705683797&xp=18&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-go-jek-india-bangalore-bengaluru-5-to-11-years-270721500847?src=jobsearchDesk&sid=1628018705683797&xp=19&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-ibm-india-pvt-limited-bangalore-bengaluru-5-to-10-years-260721907182?src=jobsearchDesk&sid=1628018705683797&xp=20&px=1']

In [21]:
# Job title

for i in url_pages:
    driver.get(i)
    title = driver.find_elements_by_xpath('//h1[@class="jd-header-title"]')
    for i in title:
        job_title.append(i.text)
job_title

['Senior Data Scientist',
 'Senior Data Scientist',
 'Senior Data Scientist',
 'Sr. Data Scientist / Tech Lead - Data Science',
 'Senior Data Scientist',
 'Data Engineers , Data Scientist and SAP',
 'Western Digital Data Scientist 3',
 'Western Digital Data Scientist',
 'Data Scientist 4',
 'Data Scientist',
 'Data Scientist 4',
 'Immediate Openings For DATA Scientist with 6 To 7 yrs of Experience',
 'Data Scientist /Sr.Data Scientist',
 'Senior Software Engineer - Data Scientist',
 'Senior Associate - Data Scientist',
 'Senior Data Scientist',
 'Senior Data Scientist',
 'Sr Data Scientist',
 'Senior Data Scientist']

In [22]:
# Job Location

for i in url_pages:
    driver.get(i)
    location = driver.find_elements_by_xpath('//span[@class="location "]')
    for i in location:
        job_location.append(i.text)
job_location

['Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'New Delhi, Bangalore/Bengaluru, Delhi / NCR',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Kolkata, Hyderabad/Secunderabad, Pune, Ahmedabad, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [23]:
# Company Name

for i in url_pages:
    driver.get(i)
    location = driver.find_elements_by_xpath('//div[@class="jd-header-comp-name"]')
    for i in location:
        company_name.append(i.text)
        
company_name

# company_name has some spaces. So, Let's saparate the company names and put in the new list company_name_
        
company_name_ = []

for i in range(0,len(company_name),2):
    company_name_.append(company_name[i])
    
company_name_

['Publicis Groupe3.3(64 Reviews)',
 'Bidgely Technologies Private Limited4.6(5 Reviews)',
 'Goals 101 Data Solutions Pvt. Ltd. 4.0(2 Reviews)',
 'Confidential',
 'RANDSTAD INDIA PVT LTD4.1(1158 Reviews)',
 'Teamware Solutions4.2(131 Reviews)',
 'Western Digital4.2(48 Reviews)',
 'Western Digital4.2(48 Reviews)',
 'Western Digital4.2(48 Reviews)',
 'HotelHub4.2(8 Reviews)',
 'Western Digital4.2(48 Reviews)',
 'Entune IT Consulting Private Limited2.8(11 Reviews)',
 'PERSOLKELLY INDIA PRIVATE LIMITED',
 'Ara Resources',
 'Novotree Minds Consulting Pvt Limited',
 'Gojek Tech',
 'GO-JEK India4.5(6 Reviews)',
 'FabHotel Aay Kay Model Town3.2(182 Reviews)',
 'GO-JEK India4.5(6 Reviews)']

In [24]:
# Job Description

for i in url_pages:
    driver.get(i)
    description = driver.find_elements_by_xpath('//div[@class="dang-inner-html"]')
    for i in description:
        job_description.append(i.text)
    
job_description

['Work location: Bengaluru (Currently, Remote)\nShift timing: 12PM to 9PM\nWork with stakeholders throughout the organization to identify opportunities for leveraging company data to drive business solutions.\nDevelop a use case roadmap for a problem area or capability for the business. Frame the business problem into a Data Science or modelling problem.\nExtract data from multiple sources. Mine and analyze data from company databases to drive optimization and improvement of product.\nWork as the data strategist, identifying and integrating new datasets that can be leveraged through our product capabilities and work closely with Client Support, Product Management and Engineering team to strategize and execute the development of data products.\nProcessing, cleansing, and verifying the integrity of data used for analysis. Undertake preprocessing of structured and unstructured data.\nData mining using state-of-the-art methods. Selecting features, building and optimizing classifiers using ML/AI techniques.\nPresent technical solutions to internal and external stakeholders in a formal setting, effectively communicating key concepts and functionalities\nEffectively manage client expectations via direct and frequent communication with high quality results\nDevelop front end deliverable solutions for stakeholders utilizing BI tools such as Tableau, Cognos, Excel, or similar\nWork on multiple assignments concurrently, while handling priorities and challenges and meeting timelines basis project plan and roadmap.\nBuild self-service tools for error detection, diagnosis, and predictive metrics.\nBuild project plans, maintain to-do list, organize work, follow coding ethics, and have an eye for detail\n\n\nQualifications\nBachelor s or Master s degree in a quantitative discipline (e.g., data science, statistics, economics, mathematics, computer science) or significant relevant coursework/experience\n4+ years professional experience in the field of data science or business intelligence\nDemonstrated proficiency in PYTHON/SCALA/SQL and BIG DATA technologies and the proven ability to program in big data/cloud technologies such as AWS SPARK; minimum 3 years of experience\nExperienced with Machine Learning algorithms such as logistic regression, linear regression, lasso regression, k-means, random forest, XG boost, KNN, SVM and neural network; minimum 2 years of experience\nAble to produce elaborate documents/narrative suggesting actionable insights and recommendations leveraging BI tools such as Tableau\nExpertise with Microsoft Office products; including Excel, PowerPoint, Word\nGreat communication skills. Excellent written and verbal communication skills for coordinating across teams.\nSelf-driven and results oriented. Willing to stretch to meet tight timelines.\nStrong team player with ability to collaborate effectively across geographies/ time zones\nGood understanding of Digital Marketing, Campaign Measurement, Web Analytics\nDesirable Qualifications:\nProfessional experience working with R\nProfessional experience working with Power BI, Cognos, Dash, Looker, Domo\nProfessional experience in fraud analytics, customer journey, attribution modeling, churn modeling, predictive analytics, customer segmentation, feature creation, statistical testing, a/b testing, production curve modeling, NLP, and partner recommendations.\nProfessional analytical consulting experience with clients in Retail, Finance, Travel, or Home and Business Services',
 'Bidgely is looking for extraordinary and dynamic Data Scientists to be part of its core team in Bangalore. You must have delivered advanced statistical and machine learning models as part of commercial products and created substantial intellectual property with business impact. You must enjoy working with large data and finding interesting patterns in the data through analytics experiments in a methodical and data driven scientific way. Be part of a highly energetic and innovative team that believes nothing is impossible with some creativity and hard work.\nResponsibilities\nResearch and develop advanced statistical and machine learning models for analysis of large-scale, high-dimensional data.\nDig deeper into data, understand characteristics of data, evaluate alternate models and validate hypothesis through theoretical and empirical approaches.\nProductize proven or working models into production quality code.\nCollaborate with product management, marketing and engineering teams in Business Units to elicit understand their requirements challenges and develop potential solutions\nStay current with latest research and technology ideas; share knowledge by clearly articulating results and ideas to key decision makers.\nFile patents for innovative solutions that add to company s IP portfolio\nRequirements\n4 to 6 years of strong experience in data mining, machine learning and statistical analysis.\nBS/MS/PhD in Computer Science, Statistics, Applied Math, or related areas from Premier institutes (only IITs / IISc / BITS / Top NITs or top US university should apply)\nExperience in productizing models to code in a fast-paced start-up environment.\nExpertise in Python programming language and fluency in analytical tools such as Matlab, R, Weka etc.\nStrong intuition for data and Keen aptitude on large scale data analysis\nStrong communication and collaboration skills.',
 'Roles and Responsibilities:\n\nWork as part of a product team in defining, prototyping and implementing data science models/algorithms as part of the product.\nBe able to research and apply the latest Machine Learning architecture solutions that work for big data Batches and Streams.\nBuild data expertise, act like an owner for the company and manage complex data systems for a product or a group of products.\nDesigning, integrating and documenting technical components for data flows or applications that perform analysis at a massive scale.\nAlong with project managers, own the business outcomes/metrics which the data science model/algorithm drives.\nBuild large scale data systems that would work across multiple geographies\nSolid understanding of the mathematics of ML - Probability, Statistics, Linear Algebra of Matrices, Modelling Hyperparameter tuning for speed of learning & model performance.\nAbility to understand business concerns and formulate them as technical problems that can be solved using Data/Math/Stats/ML.\nExperience working as part of a product team, along with engineers and product managers, to define the problem and execute the data science solution.\n\n\nDesired Candidate Profile:\n\n4+ Years of Relevant Experience.\nHands on experience of coding in Python and SQL (MySQL and Postgres)\nHands-on experience of applying and tuning the following algos of data science in multiple verticles:\nRecommendation Algos (Collaborative filtering, Content filtering (ALS etc.))\nClassification and Regression Algos\nMachine Learning Algos (XGBoost, Random Forest)\nClustering Algos (KMeans)\nDimensionality Reduction Algos (PCA)\nExperience of coding in Pyspark and Scala\nWorking knowledge of Airflow, Hadoop (HDFS) and Git\nTuning of various performance matrix (for accuracy, precision, recall, F1 Score, AUC, ROC)\nExperience in Deep Learning Algos (Neural Network)',
 'Role : Sr Data Scientist / Tech Lead - Data Science\n\nResponsibilities -\nLead a team of data scientists, machine learning engineers and big data specialists\nBe the main point of contact for the customers\nLead data mining and collection procedures\nEnsure data quality and integrity\nInterpret and analyze data problems\nConceive, plan and prioritize data projects\nBuild analytic systems and predictive models\nTest performance of data-driven products\nVisualize data and create reports\nExperiment with new models and techniques\nAlign data projects with organizational goals\n\nRequirements (please read carefully)\nVery strong in statistics fundamentals. Not all data is Big Data. The candidate should be able to derive statistical insights from very few data points if required, using traditional statistical methods.\nEducation - no bar, but preferably from a Statistics academic background (eg MSc-Stats, MSc-Econometrics etc), given the first point. Any Relevant Graduate (BE/B Tech, MCA Prefer)\nStrong expertise in Python (any other statistical languages/tools like R, SAS, SPSS etc are just optional, but Python is absolutely essential). If the person is very strong in Python, but has almost nil knowledge in the other statistical tools, he/she will still be considered a good candidate for this role.\nProven experience as a Data Scientist or similar role, for about 7-8 years\nSolid understanding of machine learning and AI concepts, especially wrt choice of apt candidate algorithms for a use case, and model evaluation.\nGood expertise in writing SQL queries (should not be dependent upon anyone else for pulling in data, joining them, data wrangling etc)\nKnowledge of data management and visualization techniques -- more from a Data Science perspective.\nShould be able to grasp business problems, ask the right questions to better understand the problem breadthwise /depthwise, design apt solutions, and explain that to the business stakeholders.\n\nWork Experience Required: 6-9 yrs.',
 'Roles and Responsibilities\nJob Description\nWhat You Will Do :Job Description: Senior Data Scientist\nOur Analytics Services group has an open, full-time position in the Bangalore region for a Senior data scientist.  The senior data scientist will be working with our clients on new product development/ new solution development as well as improve on current solutions.\nFunctional Responsibilities\n        Develop strong statistical approaches to solution development. Candidate should be well versed in executing statistical models  on Regression, Ancova, Factor analysis, Cluster analysis, Text based mining, and similar modeling approaches.\n        Evaluate model effectiveness and ability to translate the statistical requirements into excel based examples.\nCandidate should be proficient in writing good code in Python, PySpark.\n        Strong proficiency with manipulating big data with R , Python, SQL. A high comfort level with data manipulation and extraction of meaningful insights from large data and prior experience of working with large data is a plus. Experience with SAS is acceptable\nCandidate should have good working knowledge on AI and ML and should have applied these techniques on some of their recent projects\n        Being creative in identifying new techniques and processes to streamline and increase efficiency and effectiveness of current work-streams is a plus.\n        High level of attention to detail and problem solving \nProfessional requirement\nPost graduate degree in Economics, MBA, Statistics, Mathematics, Operations Research, Quantitative Analysis, or related field\n6-10 years of consolidated work experience in Analytic Industry.\nStrong statistical and quantitative analysis skills. Knowledge of Statistical Analysis techniques which are used in Marketing analytics.\nAdvanced knowledge of SQL and experience with statistical packages such as Python, Spark, PySpark, R. Experience with Oracles Exadata environment is a plus.\nExcellent data interpretation skills. Experience in using charting/reporting\nSkilled in MS-Office, specifically Excel and Powerpoint\nShould have basic knowledge of market research & any specific knowledge on Retail and FMCG/CPG/Pharma industry will be an added advantage.\nKnowledge on Retailer loyalty card data/Store transaction level data will be an added advantage.\n\n\nDesired Candidate Profile\nMust have skill: statistical modeling, pyspark, python\nNP : we can accept max 60 days. 90 days NP please avoid',
 'Dynamic recruiting professional with 7 - 10 years of high-performance tech recruiting experience with search firms and /or mid-large-sized technology companies.\nExperience in engaging and hiring the best talent for Data Engineers, Data Scientist and SAP\nOpen to learning from your peers managers, anything that helps you do your job better day in day out also often share best practices in hiring talent attraction strategies with them.\nWork well with teams as also on your own as a high-impact individual contributor.\nUse social media, job boards, Internet sourcing, and other technical means to source candidates for open jobs.\nUnderstanding of modern recruiting methods like hackathons but are equally comfortable with old school methods as well.\nWork with internal technology teams and hiring managers to assist with recruitment efforts across levels.\nWork in sync with the company-wide recruitment strategy. This may include job posting optimization, recruiting marketing channel development, search selection using job boards, digital and non-digital employment marketing, comprehensive recruitment campaign planning, talent planning, stakeholder management, etc.\nIdentify and source appropriate talent for current open roles within the organization using traditional non-traditional means of recruiting.\nProactively develop talent pools/talent communities to dip into when hiring is in full swing.\nManage the end-to-end recruitment process and life-cycle, including sourcing, initial assessments, telephonic personal interviews culminating in offers maintaining the appropriate MIS.',
 'Design, develop and maintain Machine Learning/ Analytics solution in production environments.\nArchitect and design infrastructure for big data analytics on cloud or production ready Edge cases.\nDesign and architect End-to-End platform/system for various business critical products.\nOwn maintain any/all of the various components in projects - solution architecture design, build data pipelines, ETL and web applications.\nInteract with customers to understand their analytics needs requirements for designing the product\n\n\nQualifications\nMinimum Qualification:\nProgramming Exp: 4-5 years\n3 or more years of experience in Data Science and scaling AI in areas like personalization, forecasting, experimentation, computer vision, etc.\nAbility to develop models and algorithms independently, writing your own code, developing strategy for algorithmic experimentation, and deploying in production.\nCoding experience with demonstrated expertise in at least one of the programming languages - Python, Java, R, etc.\nKnowledge of AI/ML models, frameworks and libraries/packages/APIs (e.g., scikit).\nExperience with both batch and streaming models in production.\nExperience with Hadoop, AWS or other distributed compute services.\nPreferred Qualifications:\nMaster s degree or PHD in mathematics, statistics, physics, engineering, computer science\nKnowledge of data structures, data modeling and software architecture skills.\nKnowledge and ability to explain both the code and the underlying math used algorithms/models.\nCross-functional collaboration skills.\nAnalytical and problem solving skills.\nCommunication skills, critical thinking, and strategic thinking skills above and beyond the technical knowledge and commercial implementation experience.\n\n\n\n ',
 'Design, develop and maintain Machine Learning/ Analytics solution in production environments.\nArchitect and design infrastructure for big data analytics on cloud or production ready Edge cases.\nDesign and architect End-to-End platform/system for various business critical products.\nOwn maintain any/all of the various components in projects - solution architecture design, build data pipelines, ETL and web applications.\nInteract with customers to understand their analytics needs requirements for designing the product\n\n\n\n\nQualifications\nMinimum Qualification:\nProgramming Exp: 10-12 years\n3 or more years of experience in Data Science and scaling AI in areas like personalization, forecasting, experimentation, computer vision, et',
 'Design, develop and maintain Machine Learning/ Analytics solution in production environments.\nArchitect and design infrastructure for big data analytics on cloud or production ready Edge cases.\nDesign and architect End-to-End platform/system for various business critical products.\nOwn maintain any/all of the various components in projects - solution architecture design, build data pipelines, ETL and web applications.\nInteract with customers to understand their analytics needs requirements for designing the product\n\nQualifications\nProgramming Exp: 6-8 years\nMinimum Qualification:\n3 or more years of experience in Data Science and scaling AI in areas like personalization, forecasting, experimentation, computer vision, etc.\nAbility to develop models and algorithms independently, writing your own code, developing strategy for algorithmic experimentation, and deploying in production.\nCoding experience with demonstrated expertise in at least one of the programming languages - Python, Java, R, etc.\nKnowledge of AI/ML models, frameworks and libraries/packages/APIs (e.g., scikit).\nExperience with both batch and streaming models in production.\nExperience with Hadoop, AWS or other distributed compute services.\nPreferred Qualifications:\nMaster s degree or PHD in mathematics, statistics, physics, engineering, computer science\nKnowledge of data structures, data modeling and software architecture skills.\nKnowledge and ability to explain both the code and the underlying math used algorithms/models.\nCross-functional collaboration skills.\nAnalytical and problem solving skills.\nCommunication skills, critical thinking, and strategic thinking skills above and beyond the technical knowledge and commercial implementation experience.\n\n\n\n ',

In [25]:
First_10_Jobs_Data_Scientist = pd.DataFrame(index = list(range(1,11)))

First_10_Jobs_Data_Scientist["Job Title"] = job_title[:10]
First_10_Jobs_Data_Scientist["Company Name"] = company_name_[:10]
First_10_Jobs_Data_Scientist["Job Location"] = job_location[:10]
First_10_Jobs_Data_Scientist["Job Description"] = job_description[:10]

First_10_Jobs_Data_Scientist

,Job Title,Company Name,Job Location,Job Description
1,Senior Data Scientist,Publicis Groupe3.3(64 Reviews),Bangalore/Bengaluru,"Work location: Bengaluru (Currently, Remote)\n..."
2,Senior Data Scientist,Bidgely Technologies Private Limited4.6(5 Revi...,Bangalore/Bengaluru,Bidgely is looking for extraordinary and dynam...
3,Senior Data Scientist,Goals 101 Data Solutions Pvt. Ltd. 4.0(2 Reviews),"New Delhi, Bangalore/Bengaluru, Delhi / NCR",Roles and Responsibilities:\n\nWork as part of...
4,Sr. Data Scientist / Tech Lead - Data Science,Confidential,Bangalore/Bengaluru,Role : Sr Data Scientist / Tech Lead - Data Sc...
5,Senior Data Scientist,RANDSTAD INDIA PVT LTD4.1(1158 Reviews),Bangalore/Bengaluru,Roles and Responsibilities\nJob Description\nW...
6,"Data Engineers , Data Scientist and SAP",Teamware Solutions4.2(131 Reviews),Bangalore/Bengaluru,Dynamic recruiting professional with 7 - 10 ye...
7,Western Digital Data Scientist 3,Western Digital4.2(48 Reviews),Bangalore/Bengaluru,"Design, develop and maintain Machine Learning/..."
8,Western Digital Data Scientist,Western Digital4.2(48 Reviews),Bangalore/Bengaluru,"Design, develop and maintain Machine Learning/..."
9,Data Scientist 4,Western Digital4.2(48 Reviews),Bangalore/Bengaluru,"Design, develop and maintain Machine Learning/..."
10,Data Scientist,HotelHub4.2(8 Reviews),Bangalore/Bengaluru,Data Scientist\nLocation: Bengaluru\n\n\nQuali...

### Q3: In this question you have to scrape the job-title, job-location, company_name, experience_required  for “Data Scientist” designation for first 10 job results using the filters shown below: You have to scrape the data from webpage https://www.naukri.com/

#### The location filter to be used is “Delhi/NCR”
#### The salary filter to be used is “3-6” lakhs

In [26]:
# Importing necessary Libraries

import selenium
from selenium import webdriver
import pandas as pd

In [27]:
# Let's first connect to the driver

driver = webdriver.Chrome("chromedriver.exe")
print(driver)

<selenium.webdriver.chrome.webdriver.WebDriver (session="d7bb2775d9b5eb67f6b42858b6d933b9")>

In [28]:
# Let's open the url https://www.naukri.com/

url = "https://www.naukri.com/"
driver.get(url)

In [29]:
# Writer on job title field

job_tag = driver.find_element_by_xpath('//input[@class="sugInp"]')
job_tag.send_keys("Data Scientist")

In [30]:
# Click on search button

search_click = driver.find_element_by_xpath('//button[@class="btn"]')
search_click.click()

In [32]:
# Click on 'Delhi/NCR' filter -- To select the filter box then you have to copy the full xpath

location_filter = driver.find_element_by_xpath('/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[3]/div[2]/div[3]/label/i')
location_filter.click()

In [33]:
# Click on '3-6 lakhs' filter -- To select the filter box then you have to copy the full xpath 

salary_filter = driver.find_element_by_xpath('/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[4]/div[2]/div[2]/label/i')
salary_filter.click()

In [34]:
# Empyt Lists

job_title = []
job_location = []
company_name = []
experience_required = []

In [35]:
# Job title

title = driver.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]')

for i in title:
    job_title.append(i.text)
job_title

['Data Scientist',
 'Data Scientist / Data Analyst',
 'Senior Data Scientist - Noida',
 'Only Fresher / Data Scientist / Data Analyst / Analytics - MNC Jobs',
 'Senior Data Scientist',
 'Data Scientist/Data Analyst /Business Analyst',
 'Data Scientist',
 'Data Scientist - Machine Learning/NLP',
 'Data Scientist - Machine Learning/NLP',
 'Hiring Data Scientist Develope || IDS Infotech LTD || (Permanent WFH)',
 'Hiring Data Scientist Develope || IDS Infotech LTD || (Permanent WFH)',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist ( Machine Learning , Pyspark, Cloud , DevOps)',
 'Data Scientist ( Machine Learning , Pyspark, Cloud , DevOps)',
 'We are hiring- Data Scientist- Noida',
 'Senior Data Scientist',
 'Data Scientist']

In [36]:
# Job Location

location = driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]')

for i in location:
    job_location.append(i.text)
job_location

['Gurgaon/Gurugram',
 'Gurgaon/Gurugram',
 'Noida',
 'Noida, Gurgaon/Gurugram, Delhi / NCR',
 'Hyderabad/Secunderabad, Gurgaon/Gurugram, Bangalore/Bengaluru',
 'Pune, Delhi / NCR, Mumbai (All Areas)',
 'Noida(Sector-59 Noida)',
 'Gurgaon/Gurugram',
 'Gurgaon/Gurugram',
 'Chandigarh, Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru, Delhi / NCR',
 'Chandigarh, Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru, Delhi / NCR',
 'Noida(Sector-62 Noida)\n(WFH during Covid)',
 'Noida',
 'Gurgaon/Gurugram, Bangalore/Bengaluru',
 'Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru',
 'Remote',
 'Remote',
 'Delhi / NCR\n(WFH during Covid)',
 'Delhi',
 'Gurgaon, Bengaluru']

In [37]:
# Company Name

company = driver.find_elements_by_xpath('//div[@class="mt-7 companyInfo subheading lh16"]')

for i in company:
    company_name.append(i.text)
company_name

['Decimal Technologies Pvt Ltd.\n3.9\n(32 Reviews)',
 'CARS24\n3.6\n(678 Reviews)',
 'Optum Global Solutions (India) Private Limited\n4.1\n(1232 Reviews)',
 'GABA Consultancy services',
 'inVentiv International Pharma Services Pvt. Ltd.\n4.1\n(29 Reviews)',
 'Inflexion Analytix Private Limited',
 'R Systems International Ltd.\n3.2\n(314 Reviews)',
 'TalPro',
 'TalPro',
 'IDS Infotech Ltd.\n2.9\n(127 Reviews)',
 'IDS Infotech Ltd.\n2.9\n(127 Reviews)',
 'AlgoScale Technologies Private Limited\n3.2\n(5 Reviews)',
 'Ashkom Media India Private Limited\n4.0\n(14 Reviews)',
 'UrbanClap\n3.5\n(208 Reviews)',
 'Fractal Analytics\n3.9\n(98 Reviews)',
 'JUMBO CONSULTANTS',
 'JUMBO CONSULTANTS',
 'RANDSTAD INDIA PVT LTD\n4.1\n(1158 Reviews)',
 'iNICU',
 'BlackBuck\n3.8\n(625 Reviews)']

In [38]:
# Experience Required

experience = driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi experience"]')

for i in experience:
    experience_required.append(i.text)
experience_required

['1-3 Yrs',
 '1-5 Yrs',
 '2-6 Yrs',
 '0-0 Yrs',
 '3-6 Yrs',
 '0-3 Yrs',
 '5-10 Yrs',
 '2-6 Yrs',
 '2-4 Yrs',
 '5-10 Yrs',
 '5-10 Yrs',
 '2-6 Yrs',
 '3-8 Yrs',
 '1-3 Yrs',
 '3-7 Yrs',
 '4-9 Yrs',
 '4-9 Yrs',
 '3-7 Yrs',
 '1-5 Yrs',
 '3-7 Yrs']

In [39]:
First_10_Jobs_Data_Scientist_with_filter = pd.DataFrame(index = list(range(1,11)))

First_10_Jobs_Data_Scientist_with_filter["Job Title"] = job_title[:10]
First_10_Jobs_Data_Scientist_with_filter["Company Name"] = company_name[:10]
First_10_Jobs_Data_Scientist_with_filter["Experience Required"] = experience_required[:10]
First_10_Jobs_Data_Scientist_with_filter["Job Location"] = job_location[:10]

First_10_Jobs_Data_Scientist_with_filter

,Job Title,Company Name,Experience Required,Job Location
1,Data Scientist,Decimal Technologies Pvt Ltd.\n3.9\n(32 Reviews),1-3 Yrs,Gurgaon/Gurugram
2,Data Scientist / Data Analyst,CARS24\n3.6\n(678 Reviews),1-5 Yrs,Gurgaon/Gurugram
3,Senior Data Scientist - Noida,Optum Global Solutions (India) Private Limited...,2-6 Yrs,Noida
4,Only Fresher / Data Scientist / Data Analyst /...,GABA Consultancy services,0-0 Yrs,"Noida, Gurgaon/Gurugram, Delhi / NCR"
5,Senior Data Scientist,inVentiv International Pharma Services Pvt. Lt...,3-6 Yrs,"Hyderabad/Secunderabad, Gurgaon/Gurugram, Bang..."
6,Data Scientist/Data Analyst /Business Analyst,Inflexion Analytix Private Limited,0-3 Yrs,"Pune, Delhi / NCR, Mumbai (All Areas)"
7,Data Scientist,R Systems International Ltd.\n3.2\n(314 Reviews),5-10 Yrs,Noida(Sector-59 Noida)
8,Data Scientist - Machine Learning/NLP,TalPro,2-6 Yrs,Gurgaon/Gurugram
9,Data Scientist - Machine Learning/NLP,TalPro,2-4 Yrs,Gurgaon/Gurugram
10,Hiring Data Scientist Develope || IDS Infotech...,IDS Infotech Ltd.\n2.9\n(127 Reviews),5-10 Yrs,"Chandigarh, Hyderabad/Secunderabad, Chennai, B..."

### Q4: Write a python program to scrape data for first 10 job results for Data scientist Designation in Noida location. You have to scrape company_name, No. of days ago when job was posted, Rating of the company.You have to scrape the data from webpage https://www.glassdoor.co.in/index.htm

In [40]:
# Importing necessary Libraries

import selenium
from selenium import webdriver
import pandas as pd

In [41]:
# Let's first connect to the driver

driver = webdriver.Chrome("chromedriver.exe")
print(driver)

<selenium.webdriver.chrome.webdriver.WebDriver (session="39e218b9750ea6a5546e25293ecf70e3")>

In [42]:
# Let's open the url 'https://www.glassdoor.co.in/index.htm'

url = "https://www.glassdoor.co.in/index.htm"
driver.get(url)

In [43]:
# Website is not working......

### Q5: Write a python program to scrape the salary data for Data Scientist designation in Noida location.You have to scrape the data for 10 companies. You have to scrape Company name, Number of salaries, Average salary, Min salary, Max Salary. You have to scrape the data fromwebpage https://www.glassdoor.co.in/Salaries/index.htm

In [44]:
# Importing necessary Libraries

import selenium
from selenium import webdriver
import pandas as pd

In [45]:
# Let's first connect to the driver

driver = webdriver.Chrome("chromedriver.exe")
print(driver)

<selenium.webdriver.chrome.webdriver.WebDriver (session="821da22dc93ec4ca01ea0da7ec1f9a85")>

In [46]:
# Let's open the url 'https://www.glassdoor.co.in/Salaries/index.htm'

url = " https://www.glassdoor.co.in/Salaries/index.htm"
driver.get(url)

In [47]:
# Website is not working......

## Q6 : Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes:
1. Brand
2. Product Description
3. Price
4. Discount %

In [48]:
# Importing necessary Libraries

import selenium
from selenium import webdriver
import pandas as pd

In [51]:
# Let's first connect to the driver

driver = webdriver.Chrome("chromedriver.exe")
print(driver)

<selenium.webdriver.chrome.webdriver.WebDriver (session="9effc098327f213c394be14a99ecc13f")>

In [52]:
# Let's open the url https://www.flipkart.com/

url = "https://www.flipkart.com/"
driver.get(url)

In [53]:
# Search the product name

title = driver.find_element_by_xpath('//input[@type="text"]')
title.send_keys("sunglasses")

In [54]:
# Click on search box

click = driver.find_element_by_xpath('//button[@class="L0Z3Pu"]')
click.click()

In [55]:
# Empty Lists

url_pages = []
brand_name = []
product_description = []
price = []
discount = []

In [56]:
# Page Url's (to Click on page numbers one by one)

pages = driver.find_elements_by_xpath('//nav[@class="yFHi8N"]//a') # a is becasue all url's is in a class
for i in pages:
    url_pages.append(i.get_attribute("href"))
url_pages

['https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=1',
 'https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=2',
 'https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=3',
 'https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=4',
 'https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=5',
 'https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=6',
 'https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=7',
 'https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=8',
 'https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=9',
 'https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=10',
 'https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=2']

In [57]:
# Brand names

for i in url_pages[:3]:     # [:3] means I selected 3 pages because I want to fetch only 100 details and 1 page has 40 details
    driver.get(i)
    brand = driver.find_elements_by_xpath('//div[@class="_2WkVRV"]')
    for j in brand:
        brand_name.append(j.text)
    
brand_name

['VINCENT CHASE',
 'ROYAL SON',
 'Elligator',
 'kingsunglasses',
 'Fastrack',
 'Fastrack',
 'Fastrack',
 'ROYAL SON',
 'PIRASO',
 'PIRASO',
 'Silver Kartz',
 'VINCENT CHASE',
 'ROZZETTA CRAFT',
 'kingsunglasses',
 'kingsunglasses',
 'Silver Kartz',
 'Fastrack',
 'kingsunglasses',
 'PHENOMENAL',
 'Silver Kartz',
 'Singco India',
 'Elligator',
 'Fastrack',
 'Silver Kartz',
 'Fastrack',
 'Fastrack',
 'ROZZETTA CRAFT',
 'GANSTA',
 'hipe',
 'GANSTA',
 'HIPPON',
 'kingsunglasses',
 'Fastrack',
 'ROYAL SON',
 'PIRASO',
 'NuVew',
 'NuVew',
 'PHENOMENAL',
 'Singco',
 'AISLIN',
 'AISLIN',
 'Elligator',
 'Elligator',
 'ROYAL SON',
 'Fastrack',
 'Elligator',
 'GANSTA',
 'VINCENT CHASE',
 'NuVew',
 'ROYAL SON',
 'Fastrack',
 'ROYAL SON',
 'Elligator',
 'kingsunglasses',
 'Singco India',
 'VINCENT CHASE',
 'Fastrack',
 'ROZZETTA CRAFT',
 'Fastrack',
 'Silver Kartz',
 'Fravy',
 'Flizz',
 'Fastrack',
 'Silver Kartz',
 'Villain',
 'PIRASO',
 'NuVew',
 'GANSTA',
 'NuVew',
 'ROYAL SON',
 'kingsunglasses',
 'Silver Kartz',
 'Fastrack',
 'Fastrack',
 'PIRASO',
 'kingsunglasses',
 'ROZZETTA CRAFT',
 'Fastrack',
 'Fastrack',
 'NuVew',
 'Fastrack',
 'Fastrack',
 'ROYAL SON',
 'ROYAL SON',
 'Singco India',
 'Fastrack',
 'elegante',
 'VINCENT CHASE',
 'Fastrack',
 'PHENOMENAL',
 'kingsunglasses',
 'ROYAL SON',
 'Silver Kartz',
 'ROYAL SON',
 'NuVew',
 'VINCENT CHASE',
 'Fastrack',
 'Fastrack',
 'ROYAL SON',
 'Silver Kartz',
 'ROZZETTA CRAFT',
 'hipe',
 'hipe',
 'Silver Kartz',
 'hipe',
 'Singco India',
 'United Colors of Benetton',
 'GANSTA',
 'PHENOMENAL',
 'AISLIN',
 'Fastrack',
 'Silver Kartz',
 'Fastrack',
 'Fastrack',
 'kingsunglasses',
 'NuVew',
 'Wrogn',
 'Fastrack',
 'AISLIN',
 'AISLIN']

In [58]:
# Product Description

for i in url_pages[:3]:    
    driver.get(i)
    product = driver.find_elements_by_xpath('//a[@class="IRpwTa"]')
    for j in product:
        product_description.append(j.text)
    
product_description

['UV Protection Retro Square Sunglasses (88)',
 'UV Protection Round Sunglasses (54)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Rectangular Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'Polarized, UV Protection Round Sunglasses (49)',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'Polarized Retro Square Sunglasses (54)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection Rectangular Sunglasses (Free Size)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (88)',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection Round Sunglasses (54)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (62)',
 'UV Protection, Riding Glasses, Others Aviator, Wayfarer...',
 'UV Protection Round Sunglasses (54)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Oval Sunglasses (56)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Gradient Rectangular Sunglasses (Free Si...',
 'UV Protection, Riding Glasses Aviator Sunglasses (57)',
 'Mirrored, UV Protection, Gradient Round Sunglasses (55)',
 'UV Protection Aviator Sunglasses (57)',
 'UV Protection Wayfarer Sunglasses (55)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (58)',
 'Mirrored Aviator Sunglasses (55)',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection Aviator Sunglasses (57)',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection, Mirrored Retro Square Sunglasses (53)',
 'Mirrored Aviator Sunglasses (53)',
 'Polarized, UV Protection Wayfarer, Rectangular Sunglass...',
 'UV Protection, Gradient Butterfly, Retro Square Sunglas...',
 'Mirrored Round Sunglasses (53)',
 'UV Protection, Riding Glasses Rectangular, Retro Square...',
 'UV Protection Retro Square Sunglasses (88)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (55)',
 'UV Protection, Mirrored Wayfarer Sunglasses (53)',
 'UV Protection Aviator Sunglasses (57)',
 'UV Protection, Gradient Wayfarer Sunglasses (55)',
 'UV Protection Aviator Sunglasses (58)',
 'Polarized, UV Protection Round Sunglasses (49)',
 'UV Protection Round Sunglasses (53)',
 'Mirrored, UV Protection Wayfarer, Wayfarer, Wayfarer, W...',
 'UV Protection Aviator Sunglasses (Free Size)',
 'Polarized Retro Square Sunglasses (54)',
 'UV Protection Shield Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Rectangular Sunglasses (F...',
 'UV Protection Wrap-around Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (88)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection Rectangular Sunglasses (59)',
 'UV Protection Aviator Sunglasses (62)',
 'Others Retro Square Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (32)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (56)',
 'UV Protection, Riding Glasses Aviator Sunglasses (57)',
 'UV Protection, Mirrored, Night Vision, Riding Glasses S...',
 'UV Protection Rectangular Sunglasses (58)',
 'UV Protection Rectangular Sunglasses (Free Size)',
 'UV Protection Oval Sunglasses (56)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Shield Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (57)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (57)',
 'Gradient, UV Protection Round, Oval, Cat-eye Sunglasses...',
 'UV Protection Retro Square Sunglasses (88)',
 'Riding Glasses, Others, UV Protection Wrap-around Sungl...',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection Clubmaster Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (Free Size)',
 'Polarized, UV Protection Round Sunglasses (49)',
 'UV Protection Oval Sunglasses (56)',
 'UV Protection Wayfarer Sunglasses (55)',
 'UV Protection, Mirrored Aviator Sunglasses (58)',
 'Polarized Retro Square Sunglasses (54)',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (61)',
 'Polarized Rectangular Sunglasses (65)',
 'UV Protection Aviator Sunglasses (88)',
 'UV Protection, Gradient Rectangular Sunglasses (Free Si...',
 'UV Protection, Night Vision, Gradient, Mirrored Round, ...',
 'Mirrored, Gradient, Riding Glasses Round Sunglasses (55...',
 'UV Protection Aviator Sunglasses (62)',
 'UV Protection, Gradient, Mirrored, Riding Glasses Recta...',
 'Riding Glasses, UV Protection, Others Aviator Sunglasse...',
 'Mirrored Rectangular Sunglasses (53)',
 'UV Protection, Riding Glasses Aviator Sunglasses (57)',
 'UV Protection Round Sunglasses (53)',
 'UV Protection Oval Sunglasses (58)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Oval Sunglasses (56)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Rectangular Sunglasses (55)',
 'UV Protection Aviator Sunglasses (57)',
 'Mirrored Wayfarer Sunglasses (52)',
 'UV Protection Sports Sunglasses (Free Size)',
 'UV Protection Oval Sunglasses (60)',
 'Polarized, UV Protection Wayfarer, Rectangular Sunglass...']

In [59]:
# Price

for i in url_pages[:3]:    
    driver.get(i)
    pri = driver.find_elements_by_xpath('//div[@class="_30jeq3"]')
    for j in pri:
        price.append(j.text)
    
price

['₹799',
 '₹599',
 '₹295',
 '₹299',
 '₹758',
 '₹513',
 '₹509',
 '₹664',
 '₹237',
 '₹237',
 '₹246',
 '₹799',
 '₹499',
 '₹210',
 '₹299',
 '₹255',
 '₹1,085',
 '₹225',
 '₹399',
 '₹255',
 '₹214',
 '₹331',
 '₹655',
 '₹284',
 '₹733',
 '₹558',
 '₹404',
 '₹251',
 '₹199',
 '₹284',
 '₹257',
 '₹349',
 '₹1,010',
 '₹379',
 '₹237',
 '₹275',
 '₹215',
 '₹399',
 '₹239',
 '₹1,085',
 '₹545',
 '₹312',
 '₹398',
 '₹599',
 '₹647',
 '₹328',
 '₹211',
 '₹799',
 '₹185',
 '₹217',
 '₹1,115',
 '₹664',
 '₹295',
 '₹299',
 '₹334',
 '₹799',
 '₹759',
 '₹449',
 '₹522',
 '₹255',
 '₹169',
 '₹379',
 '₹1,021',
 '₹255',
 '₹599',
 '₹237',
 '₹235',
 '₹251',
 '₹345',
 '₹474',
 '₹210',
 '₹284',
 '₹826',
 '₹853',
 '₹331',
 '₹349',
 '₹499',
 '₹655',
 '₹1,779',
 '₹275',
 '₹782',
 '₹503',
 '₹699',
 '₹599',
 '₹293',
 '₹676',
 '₹199',
 '₹799',
 '₹759',
 '₹319',
 '₹349',
 '₹664',
 '₹284',
 '₹265',
 '₹185',
 '₹799',
 '₹546',
 '₹629',
 '₹699',
 '₹255',
 '₹499',
 '₹210',
 '₹189',
 '₹255',
 '₹299',
 '₹232',
 '₹1,574',
 '₹251',
 '₹297',
 '₹545',
 '₹758',
 '₹284',
 '₹633',
 '₹576',
 '₹210',
 '₹275',
 '₹695',
 '₹771',
 '₹725',
 '₹1,085']

In [60]:
# Discount

for i in url_pages[:3]:    
    driver.get(i)
    disc = driver.find_elements_by_xpath('//div[@class="_3Ay6Sb"]')
    for j in disc:
        discount.append(j.text)
    
discount

['60% off',
 '70% off',
 '88% off',
 '88% off',
 '15% off',
 '35% off',
 '36% off',
 '66% off',
 '85% off',
 '85% off',
 '83% off',
 '60% off',
 '77% off',
 '82% off',
 '88% off',
 '78% off',
 '16% off',
 '79% off',
 '80% off',
 '78% off',
 '69% off',
 '74% off',
 '27% off',
 '76% off',
 '18% off',
 '30% off',
 '79% off',
 '80% off',
 '86% off',
 '85% off',
 '78% off',
 '78% off',
 '22% off',
 '74% off',
 '85% off',
 '70% off',
 '72% off',
 '80% off',
 '76% off',
 '72% off',
 '64% off',
 '87% off',
 '73% off',
 '70% off',
 '28% off',
 '86% off',
 '78% off',
 '60% off',
 '75% off',
 '78% off',
 '14% off',
 '66% off',
 '88% off',
 '80% off',
 '72% off',
 '60% off',
 '15% off',
 '79% off',
 '41% off',
 '78% off',
 '81% off',
 '82% off',
 '21% off',
 '78% off',
 '20% off',
 '85% off',
 '75% off',
 '80% off',
 '62% off',
 '68% off',
 '83% off',
 '76% off',
 '8% off',
 '5% off',
 '87% off',
 '70% off',
 '77% off',
 '18% off',
 '11% off',
 '78% off',
 '2% off',
 '37% off',
 '53% off',
 '70% off',
 '82% off',
 '15% off',
 '80% off',
 '60% off',
 '15% off',
 '84% off',
 '78% off',
 '66% off',
 '76% off',
 '79% off',
 '78% off',
 '60% off',
 '31% off',
 '30% off',
 '65% off',
 '78% off',
 '77% off',
 '78% off',
 '86% off',
 '78% off',
 '76% off',
 '84% off',
 '66% off',
 '80% off',
 '87% off',
 '77% off',
 '15% off',
 '76% off',
 '29% off',
 '27% off',
 '83% off',
 '70% off',
 '73% off',
 '14% off',
 '70% off',
 '72% off']

In [61]:
Flipcart_100_Sunglasses = pd.DataFrame(index = list(range(1,101)))

Flipcart_100_Sunglasses["Brand"] = brand_name[:100]
Flipcart_100_Sunglasses["Product Description"] = product_description[:100]
Flipcart_100_Sunglasses["Price"] = price[:100]
Flipcart_100_Sunglasses["Discount"] = discount[:100]

Flipcart_100_Sunglasses

,Brand,Product Description,Price,Discount
1,VINCENT CHASE,UV Protection Retro Square Sunglasses (88),₹799,60% off
2,ROYAL SON,UV Protection Round Sunglasses (54),₹599,70% off
3,Elligator,"Mirrored, UV Protection Wayfarer Sunglasses (F...",₹295,88% off
4,kingsunglasses,UV Protection Wayfarer Sunglasses (Free Size),₹299,88% off
5,Fastrack,UV Protection Rectangular Sunglasses (Free Size),₹758,15% off
...,...,...,...,...
96,VINCENT CHASE,Polarized Rectangular Sunglasses (65),₹799,60% off
97,Fastrack,UV Protection Aviator Sunglasses (88),₹546,31% off
98,Fastrack,"UV Protection, Gradient Rectangular Sunglasses...",₹629,30% off
99,ROYAL SON,"UV Protection, Night Vision, Gradient, Mirrore...",₹699,65% off
100,Silver Kartz,"Mirrored, Gradient, Riding Glasses Round Sungl...",₹255,78% off

### Q7: Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to go the link: https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace. 

### You have to scrape Ratings, Review Summary & Full Review.

In [62]:
# Importing necessary Libraries

import selenium
from selenium import webdriver
import pandas as pd

In [63]:
# Let's first connect to the driver

driver = webdriver.Chrome("chromedriver.exe")
print(driver)

<selenium.webdriver.chrome.webdriver.WebDriver (session="c27ddc546cc408f7680678496566de43")>

In [64]:
# Let's open the given url...

url = 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace.'
driver.get(url)

In [65]:
# Empty lists

url_page = []
rating = []
review_summary = []
full_summary = []

In [66]:
# Click on All Reviews

pages = driver.find_element_by_xpath('//div[@class="_3UAT2v _16PBlm"]')
pages.click()

In [67]:
# All pages links

urls = driver.find_elements_by_xpath('//nav[@class="yFHi8N"]//a')
for i in urls:
    url_page.append(i.get_attribute("href"))
url_page

['https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=1',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=2',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=3',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=4',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=5',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=6',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=7',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=8',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=9',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=10',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=2']

In [68]:
# Ratings

for i in url_page:
    driver.get(i)
    ratings = driver.find_elements_by_xpath('//div[@class="_3LWZlK _1BLPMq"]')
    for j in ratings:
        rating.append(j.text)
rating

['5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '4',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '3',
 '5',
 '4',
 '5',
 '5',
 '5',
 '3',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5']

In [69]:
# Review Summary

for i in url_page:
    driver.get(i)
    summary = driver.find_elements_by_xpath('//p[@class="_2-N8zT"]')
    for j in summary:
        review_summary.append(j.text)
review_summary

['Simply awesome',
 'Brilliant',
 'Perfect product!',
 'Fabulous!',
 'Worth every penny',
 'Great product',
 'Worth every penny',
 'Good choice',
 'Highly recommended',
 'Perfect product!',
 'Perfect product!',
 'Best in the market!',
 'Highly recommended',
 'Classy product',
 'Highly recommended',
 'Worth every penny',
 'Perfect product!',
 'Simply awesome',
 'Worth every penny',
 'Terrific',
 'Nice product',
 'Wonderful',
 'Classy product',
 'Brilliant',
 'Must buy!',
 'Good choice',
 'Perfect product!',
 'Wonderful',
 'Terrific purchase',
 'Great product',
 'Simply awesome',
 'Mind-blowing purchase',
 'Terrific purchase',
 'Simply awesome',
 'Good quality product',
 'Very poor',
 'Perfect product!',
 'Must buy!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Mind-blowing purchase',
 'Wonderful',
 'Worth every penny',
 'Great product',
 'Very Good',
 'Perfect product!',
 'Classy product',
 'Perfect product!',
 'Just wow!',
 'Awesome',
 'Terrific',
 'Terrific purchase',
 'Awesome',
 'Classy product',
 'Brilliant',
 'Perfect product!',
 'Awesome',
 'Perfect product!',
 'Excellent',
 'Very poor',
 'Fabulous!',
 'Excellent',
 'Must buy!',
 'Value-for-money',
 'Brilliant',
 'Terrific purchase',
 'Good quality product',
 'Perfect product!',
 'Value-for-money',
 'Just wow!',
 'Super!',
 'Awesome',
 'Best in the market!',
 'Highly recommended',
 'Mind-blowing purchase',
 'Must buy!',
 'Excellent',
 'Excellent',
 'Pretty good',
 'Wonderful',
 'Worth every penny',
 'Worth every penny',
 'Nice product',
 'Mind-blowing purchase',
 'Fabulous!',
 'Classy product',
 'Does the job',
 'Awesome',
 'Pretty good',
 'Terrific',
 'Terrific purchase',
 'Awesome',
 'Decent product',
 'Super!',
 'Fabulous!',
 'Just wow!',
 'Mind-blowing purchase',
 'Excellent',
 'Excellent',
 'Wonderful',
 'Perfect product!',
 'Best in the market!',
 'Highly recommended',
 'Classy product',
 'Highly recommended',
 'Worth every penny',
 'Perfect product!',
 'Simply awesome',
 'Worth every penny',
 'Terrific']

In [70]:
# Full Summary

for i in url_page:
    driver.get(i)
    full = driver.find_elements_by_xpath('//div[@class="t-ZTKy"]')
    for j in full:
        full_summary.append(j.text.replace("\n",""))
full_summary

['Really satisfied with the Product I received... It’s totally genuine and the packaging was also really good so if ur planning to buy just go for it.',
 'The Best Phone for the MoneyThe iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.Compelling ultra-wide cameraNew Night mode is excellentLong battery life',
 'Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .',
 'This is my first iOS phone. I am very happy with this product. Very much satisfied with this. I love this phone.',
 'Previously I was using one plus 3t it was a great phoneAnd then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD displayBut I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product redMy experience after using 3 weeks1. The delivery ...READ MORE',
 'Amazing Powerful and Durable Gadget.I’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone.I shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years.Don’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb.I’ve attached my puppy pics and no fi...READ MORE',
 'i11 is worthy to buy, too much happy with the product. Thank u flipkart I received the item on time..loved it..',
 'So far it’s been an AMAZING experience coming back to iOS after nearly a decade but it’s not as versatile as android though phone is sturdy dropped it accidentally a couple of times and nothing happened fortunately camera is awesome',
 'iphone 11 is a very good phone to buy only if you can compromise for the display. The display on this is device is pretty good but you can get other options with better displays in this price segment.If you can survive with an HD+ LCD panel with thicker bezels and a notch up top then this is a very good phone for you.Cameras are awesome, battery backup excellent, great performance and a decent premium look. Good job Apple !',
 'It’s a must buy who is looking for an upgrade from previous generation of iPhones. If you are using XR then still you can hold on for sometime and upgrade to 2020 model else this phone is a must buy . Camera quality is amazing and wide angle is something to count upon. Performance wise it’s amazing and feels premium while holding in hand. So a big YES for this device. Go for 128 GB variant as the 4K videos will occupy lots of space and the storage can get over very quickly. Try to buy it with...READ MORE',
 'Value for money❤️❤️Its awesome mobile phone in the world ...Display was very good and bright ..Trust me freinds you r never regret after Buying..Just go for it....I love this phone and i switch to iphone x to 11',
 'Great iPhone very snappy experience as apple kind. Upgraded from iPhone 7.Pros-Camera top class- Battery top performed-Chipset no need to say as apple kind-Security as you expect from apple- Display super bright industry leading colouraccuracy and super responsive-Build quality as expect from apple sturdypremium durable beautiful stylish.-Os most stable os in smartphone industryCons-No 5G-Display is not based on OLED technology-Charger headphones and 1 apple stic...READ MORE',
 'What a camera .....just awesome ..you can feel this iPhone just awesome . Good for gaming also ...try pubg in hd it’s just wow',
 'Totally in love with this ❤ the camera quality is amazing just love it 😘😘😘 itsss dammnnnnnn amazing... Must buy iPhone 11 this is my best experience ever ☀👌👌🧡🧡🧡🧡🧡 thanku apple ❤',
 "It's my first time to use iOS phone and I am loving my upgradation 😍😍 I love the color, I love the assebility of the phone....I need to learn more about its functionality, but as far as I have seen, it's quite easy and it has a lot of functions to work on, specially if you are a content writer or a blogger you get a lot of content creation platforms and they are really amazing.This phone not only for good quality photography but a lot of other task too.😍💯",
 'Best budget Iphone till date ❤️ go for it guys without second thought. Let me explain you guys about Camera, Display, battery, and performance.Camera: at this price range there is no comparison of camera, you’ll love the picture quality as well as video quality. I am a Vlogger I wanted an iPhone with 4k video by front camera and I got this phone and I am more than happy 😃Battery: I use this phone roughly as I am active social media person and I have a youtube channel. so the battery ba...READ MORE',
 "Iphone is just awesome.. battery backup is very very nice.. continuously for 10 hours we can use it.camera is just awesome.. display is just fab.i love it alot..i had to wait 15 days for it as i pre ordered it..overalll it's worth the price..these all images are clicked by my iPhone..and i love it.",
 'Excellent camera, good performance, no lag. The lcd display is also good.. but difference come when we watch movie in prime and Netflix, the colours are not vibrant.. as we see in amoled display.. and the charger in box is of 5 watts.. takes more than 3 hours to charge from 0 to 100.. so guys be prepare to buy 18 watts charger . Finally I am an android user, it was my first Iapple phone, I promise u guys the iOS is so smooth.. overall the phone is damn good.... close eyes to buy it.. thanks t...READ MORE',
 'It’s been almost a month since I have been using this phone. I upgraded from an iPhone 8. The main issue with my 8 was battery and this phone is just awesome when it comes to battery. It lasts a day and a half for me with my regular use , internet connected always with 4gCan’t move forward without saying this. Battery of this phone is a life saver when I am traveling or at work when I don’t get the option to chargeCamera is superb. Front cam selfies and back cam photos are just awesome....READ MORE',
 'Really worth of money. i just love it. It is the best phone ever.',
 'Awesome Phone. Slightly high price but worth. Better than iPhone XR.Camera is superb and wide angle camera is very clear.12MP selfie camera is also very good.A13 Chip gives a very good and smooth performance.',
 'This is my first ever I phone. Before this I was using my google nexus 5. But moving from android to iOS is a great experience. It’s worth at this price. I will highly recommend it if you want to move to iOS. The best part of this phone is it’s camera and it’s battery life. This two things have won my heart. I loved it. Happy to have it in my hand. Still exploring its features. And can’t forget to mention Flipkart service. Very prompt service and fast delivery.',
 'Superb Product !!!A big and worthy upgrade from mi 3S to iphone 11 .Totally loved it !',
 'I have migrated from OP 7pro... and trust me, iPhone 11 is totally worth it.. following are the reasons:-1)there is ABSOLUTELY NO ISSUE WITH THE DISPLAY... its crisp, sharp and I found it to be much much better than OP7 pro. Netflix, Prime video all run crisply... you won’t miss a thing. True Tone works flawlessly...the display brightness is perfect. OP have not calibrated their screens properly.2) iPhone 11 series have really good cameras... others have spoken in depth about them.3) bat...READ MORE',
 'It’s an amazing product from apple and the camera is simply superb. Phone is faster.Night shot is simply superb and detailing and colour differentiation from camera is an added advantageThis review I have written from iPhone 11 only and I am glad to say outside.Cons wise if we see HD+ display only, no battery percentage indicator as in older iPhone 8.No assistive touch control button in itNo oleophobic coating on back panel glass and finger prints are visible but since I bought mint gr...READ MORE',
 'Looking so good 👍 😍 super 👌 stylish 😎 phoneClean box 📦 good 👍 delivery 👌 fast deliveryOriginal box Original iphone 📱 👌 😍😍😍',
 'After 1 month use I found camera quality best compared to my previous Samsung note 10+.Display not good as note 10 also charging too slow.Apple should add fast charger like 11 plus and pro.Best phone for daily use',
 'I just directly switch from iphone 6s to iphone 11 .The best premium smartphone I recommend to everyone. Excellent quality and colors the iphone have in 11 series.Camera quality is just awesome and the major feel when we hold in our hands. The sound quality and volume is also higher then the previous models.I will recommend to buy iphone 11 instead of pro models , there is nothing much difference as this model contains everything which fulfill our needs.Only one thing that I dislike abo...READ MORE',
 'Upgraded from iphone 6 to 11 best phone for iphone users battery is much better than other iphones camera is awesome love to use it.camera is so clear in night.',
 'Well you all know the specifications . One of a kind. Best iPhone till date. Many enhancements to the camera app with many options. Love the glass body with matte finish in the lens area on the back. Lovely colours to choose from. Best battery in an iPhone till date, enough to last more than a day in normal usage. I tested my iPhone 11 battery and lasted for than 24 hours after full charge still with 30% battery charge left. Watched movies for some time. Normal usage on calls, browsing, musi...READ MORE',
 "It's very high performances devise i am like the service of flipkart delevary very fast and packing very nice perfect phone",
 'This will help you more. See if you are planning to buy iPhone 11. I will say. Yes. But there are some plans I just want to disclose before you buy. 1) If you are an existing iPhone X/XS/XS Max/ XR user, better you guys do not think it to buy. You guys have more or less better gadget. 2) If you are an android user and planning to buy premium phone. I will suggest them to please buy iPhone instead of buying an Android. I bet you will never go back to android after using IOS. Now I want to shar...READ MORE',
 'The built quality is not very premium.The battery back is great .The LCD panel is not so sharp but the brightness level is very High .Camera is super duper awesome.The red colour which people think is bright is actually very soothing and excellent colour to choose from .The A13 Bionic chip is really a flagship processor and can beat any phone which even has 12 gb ram .Camera module is very great and looks very stylish.',
 'Really good actually this is my first apple product am using its really awesome performance wise excellent. Am really happy with this iphone11',
 'it is very good at performance. Camera is best like before and very smooth response even in water. Don’t buy 12 mini buy iPhone 11 , it is far better than 12 mini believe me ! Have a nice day \uf8ff ☺️',
 'Reviewing again after 5 months. At the beginning the battery and performance was good but it degraded soon. Also I was facing heating issues. The mobile will heat up like a stove sometimes. You cannot even play Pubg even in low settings properly, performance is not a problem but heating is. Also if you play that game for 10 mins the brightness will be automatically down due to over heating even when the auto brightness is set to off. This will not be solved even if u manually increase the bri...READ MORE',
 'It is just awesome mobile for this price from Apple,After 10 days reviewBattery enough for 1 day even 24*7 Internet will be on and mostly internet usageCamera is just awesome cool , android 64 MP is equal to this just 12 MPA13 Bionic chip will give more high performance without hangingAudio stereo speakers will give Dolby atoms sound with crystal clearVideo recording is like cinematic shots of every sec can be a 4K 60fps. Just awesome this phoneiPhone 11 loved one',
 'Best Apple iPhone that i have bought at a very reasonable price, camera quality is next level just awesome n of superior quality android phones not even close(RIP) to that and also battery is really good but packaging by Flipkart of iPhone was very poor of such a expensive product, firstly im bit worried about the quality of product if i purchased it through online how was the product but i think now this was mine best decision to bought it through Flipkart online because i got genuine Apple...READ MORE',
 "I can say I'm damn impressed with iPhone 11. As they says iPhone 11 have the toughest glass ever in the smartphone which you'll find on the front and back and it's totally smooth. The fit and finish is full apple quality - there's no sense that any cheaping out has happened in the construction. Without saying it's camera features this review won't complete. The iPhone 11 has a dual camera system, consisting of a wide angle len's that's pretty much same as found on the iPhone XR last year, but...READ MORE",
 'Best Quality Product OF iPhone Series , Sound Quality & Camera quality is very awesome, Battery Life is very Sufficient for 24 hr Backup With Full Internet Access , I love this this Product too much , It is very fast & making me Very fast in all my daily RoutineHighlights;1.Camera: 5 STAR2.Video Recording: 5 star3.Night mODE sHOOTING & Camera:4 star4. Audio Quality: Awesome5. Battery : 5 Star6. Touch:5 Star7. Processor: Very FastThe M...READ MORE',
 'First thanks to Flipkart for this amazing deal and phone is outstanding. I upgraded from iPhone 7 and this is like very big upgrade. But the packaging was very basic I expected a good packaging as they only wrapped one layer of bubble wrap which I don’t think is enough to protect this expensive phone. And I recommend this phone and seller as well.And I’m posting this review after using it for 4 days.',
 'Superfast delivery by Flipkart. Thanks.1. iPhone 11 is a pretty solid phone for the money you are paying.2. All the bad reviews about the display is confusing. It’s not that bad.3. I switched from a Oneplus 7t. I have no complaints about the display quality of iPhone. Yes, it’s not OLED, so, we are missing on the deep blacks. But that’s it. It is a very colour accurate display. Gets adequately bright and I could not find any pixelation.4. Performance is one of the best, if not best, in ...READ MORE',
 'Smooth like butter, camera like fantabulous, sound is crystal clear & its red color is damn attractive, i am just loving it. Must buy if you love photography.Lucky to get it in sale, thank you Flipkart.',
 "Again back to apple iphone after a gap of 2-3 years. It's pleasure to use iOS and the quality product by Apple. Iphone 11 still works like a beast in 2021 also. It really capable of doing day to day usage as well as hard core gaming. Battery is awesome. I'm really too much satisfied with it. Apart fto the very gorgious IPS LCD (AMOLED will be better) everything is mind boggling. Iphone💕.",
 'impressive super phone and best in class camera ,sound and face unlock is super fast just see and phone is unlock and fast in daily apps use',
 'Battery backup is extraordinary, camera is decent & performance offered by A13 bionic is awsome. The display is good in practical usage like the visibility of display is very good in direct sun light compare to pro models. Iam extremely satisfied for the money I spent.',
 'Well while switching from android to iOS the first thing you need to be careful about is that you will loose all your whatsapp chat backups as both are different operating systems. Camera clarity is awesome and though being an lcd screen clarity and resolution is good. Battery backup is also good unlike previous gen iPhone. So far the experience is good will Padre after a few months of usage.P.S the black is more of a dark grey shade and not jet black',
 'In love with this iphone great performance,camera ,battery everything. Go for it have a uncompareble battery backup, no doubts in iPhone camera here You can see the picture which is shot on my iPhone In love with this iphone great performance,camera ,battery everything. Go for it have a uncompareble battery backup, no doubts in iPhone camera here You can see the picture which is shot on my iPhone In love with this iphone great performance,camera ,battery everything. Go for it have a uncompare...READ MORE',
 'Best in class. Battery backup is good especially when you play games like Pubg COD. But it is sort of heavy when you hold in hands. Portrait mode is best to click pictures. Stage light effect is awesome. Try to click photos outside in nature because photos inside home or room will not give you the quality in any phone even in DSLR.',
 'Very excited to have this phone. This phone has the real power unlike the android phones having SD 855 . The battery life is very good and the camera quality is excellent as comapred to redmi and other phones except google pixel. I M enjoying every single bit of it. Would recommed only if you have the budget.',
 "I upgraded (downgraded?) from my iPhone X since the phone fell down and I didn't want to repair the screen. The box that the phone came in was super slim and I was worried that there'd be no 5W charger with it and my fears were confirmed. However, thankfully I had the 18W USB-C PD charger from Apple which I bought for my iPhone X and it worked perfectly. The charging time is as lethargic as ever though and it takes about 1:30 mins or even 2 hours depending on charge remaining. I'll list some ...READ MORE",
 'Its Very awesome product working and good camera quality and all about best product and also flipkart is very great deal and offer nice price',
 'I am using this phone for 5 days and its one of the best camera out there ❤️ the screen is not oled and i am coming from iphone xs so its little bit not up to the mark i would sayBut overall value for money💕😍the battery back up is far better than my iphone xs and its worth in my apple ecosystem💫❤️if u are an apple User and have the eco system then go for it❤️though i will be getting the new iphone but its pretty good💫',
 'Best and amazing product.....phone looks so premium.... battary is also good as expected .... Wide angle camera is so addictive ...if you are a IOS lover....then this phone will be the best choice for you all!!💯🔥',
 'Excellent camera and display touching very nice and smooth very improvement against iPhone XR and new processor is very fast',
 'Awesome purchase. Amazing phone with good battery backup. It’s a top notch device. White colour looks amazing. Phone has a few extra feature than iPhone XR. Overall, this is value for money',
 'Always love the apple products, upgraded from old iPhone 6S plus to this after having my first baby. I just love to click baby’s photos with it. Overall I just love this phone. Battery back up is okay, sound quality is good. Haven’t tested yet waterproof yet. Only one thing I hate is apple could have given charger & headphones in box.',
 'Value for money5 star ratingExcellent cameraBattery backup full day in single charge.Tougher and water resistant design, glossy back.The screen has excellent brightness and contrast.Apple A13 Bionic is the fastest smartphone chip on the planet.Excellent battery life, fast charging support.Stereo speakers with great quality.',
 'Amazing camera and feel super machine I am not describe my feeling but this is amazing Phone I am so lucky I have this',
 'Please DONT buy from here,I purchased Apple iPhone 11. with an exchange of IPhone 7, the exchange did not go well, iPhone 7 had a small scratch out side screen which i could never identify till date, but the FLIPKART person could, so he reduced 50% from exchange rate. I decided not to trade in, but paid money.iPhone 11 Detail Below---------------------------------------------It came with no charging, then i have put for charging, it took lot of time for charging, the phone also showe...READ MORE',

In [71]:
# Data Frame

Data_100_reviews = pd.DataFrame(index = list(range(1,101)))

Data_100_reviews["Ratings"] = rating[:100]
Data_100_reviews["Review Summary"] = review_summary[:100]
Data_100_reviews["Full Summary"] = full_summary[:100]


Data_100_reviews

,Ratings,Review Summary,Full Summary
1,5,Simply awesome,Really satisfied with the Product I received.....
2,5,Brilliant,The Best Phone for the MoneyThe iPhone 11 offe...
3,5,Perfect product!,Amazing phone with great cameras and better ba...
4,5,Fabulous!,This is my first iOS phone. I am very happy wi...
5,5,Worth every penny,Previously I was using one plus 3t it was a gr...
...,...,...,...
96,5,Just wow!,The ultimate performanceCamera is superbThe ba...
97,5,Mind-blowing purchase,Excellent camera 📸 And Display touching very N...
98,5,Excellent,A perfect phone and a good battery super camer...
99,5,Excellent,Value for money product. This iphone 11 is rea...
100,5,Wonderful,Super and marvellous phone look very cute and ...

### Q8: Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field. You have to scrape :-
1. Brand 
2. Product Description
3. Price
4. discount %

In [72]:
# Importing necessary Libraries

import selenium
from selenium import webdriver
import pandas as pd

In [73]:
# Let's first connect to the driver

driver = webdriver.Chrome("chromedriver.exe")
print(driver)

<selenium.webdriver.chrome.webdriver.WebDriver (session="0c0812e0c2f42311d1fa8f8eafb7e352")>

In [74]:
# Let's open the webpage 'https://www.flipkart.com/'

url = 'https://www.flipkart.com/'
driver.get(url)

In [75]:
# First click on the X mark to decline the login page

decline_login_page = driver.find_element_by_xpath('//button[@class="_2KpZ6l _2doB4z"]')
decline_login_page.click()

In [76]:
# Enter 'sneakers' in the search bar

sneakers = driver.find_element_by_xpath('//input[@type="text"]')
sneakers.send_keys("sneakers")

In [77]:
# Click on the search icon

click = driver.find_element_by_xpath('//button[@class="L0Z3Pu"]')
click.click()

In [78]:
# Empty Lists

url_pages = []
brand_name = []
product_description = []
price = []
discount = []

In [79]:
# Page Links

url = driver.find_elements_by_xpath('//nav[@class="yFHi8N"]//a')
for i in url:
    url_pages.append(i.get_attribute("href"))

url_pages

['https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=1',
 'https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=2',
 'https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=3',
 'https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=4',
 'https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=5',
 'https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=6',
 'https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=7',
 'https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=8',
 'https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=9',
 'https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=10',
 'https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=2']

In [80]:
# Brand

for i in url_pages[:3]:
    driver.get(i)
    brand = driver.find_elements_by_xpath('//div[@class="_2WkVRV"]')
    for i in brand:
        brand_name.append(i.text)
    
brand_name

['aadi',
 'Xtoon',
 'Numenzo',
 'ASTEROID',
 'World Wear Footwear',
 'bluemaker',
 'Chevit',
 'India hub',
 'Numenzo',
 'Shoes Bank',
 'Magnolia',
 'EZDEZARIO',
 'PEHANOSA',
 'Red Rose',
 'Chevit',
 'Modern Fahion Shoes',
 'India hub',
 'BRUTON',
 'Chevit',
 'Echor',
 'believe',
 'BRUTON',
 'Chevit',
 'TR',
 'Robbie jones',
 'Nilatin',
 'Nilatin',
 'URBANBOX',
 'Kraasa',
 'Zsyto',
 'Chevit',
 'U.S. POLO ASSN.',
 'ROCKFIELD',
 'SCATCHITE',
 'RODDICK SHOES',
 'Absolutee shoes',
 'CALCADOS',
 'Echor',
 'World Wear Footwear',
 'Baogi',
 'Jokatoo',
 'RODDICK SHOES',
 'bluemaker',
 'luxury fashion',
 'Longwalk',
 'BIRDE',
 'tigonis',
 'aadi',
 'SPARX',
 'restinfoot',
 'Ktiz',
 'luxury fashion',
 'SPARX',
 'Edoeviv',
 'Labbin',
 'India hub',
 'Chevit',
 'T-ROCK',
 'World Wear Footwear',
 'Xtoon',
 'World Wear Footwear',
 'Nilatin',
 'Zsyto',
 'India hub',
 'Robbie jones',
 'Magnolia',
 'SPARX',
 'EZDEZARIO',
 'Zorth',
 'Bonexy',
 'Chevit',
 'Modern Fahion Shoes',
 'Fzzirok',
 'Zsyto',
 'Zixer',
 'luxury fashion',
 'ROCKFIELD',
 'Robbie jones',
 'Ktiz',
 'Echor',
 'STRANGER BROTHERS',
 'Ktiz',
 'WRIZT',
 'India hub',
 'ESSENCE',
 'PUMA',
 'SPARX',
 'aadi',
 'Chevit',
 'Chevit',
 'Numenzo',
 'Xtoon',
 'SPARX',
 'Chevit',
 'PUMA',
 'India hub',
 'HOTSTYLE',
 'REEBOOT',
 'luxury fashion',
 'STRANGER BROTHERS',
 'Rising Wolf',
 'ESSENCE',
 'PUMA',
 'EZDEZARIO',
 'HOCKWOOD',
 'PUMA',
 'FILA',
 'Modern Fahion Shoes',
 'HOCKWOOD',
 'Numenzo',
 'Chevit',
 'Echor',
 'SPARX',
 'Robbie jones',
 'D-SNEAKERZ',
 'TR',
 'TORRY',
 'PUMA',
 'ASIAN',
 'URBANBOX']

In [81]:
# Product Description

for i in url_pages[:3]:
    driver.get(i)
    description = driver.find_elements_by_xpath('//a[@class="IRpwTa"]')
    for i in description:
        product_description.append(i.text)
    
product_description

['Sneakers For Men',
 'Luxury Fashionable casual sneaker shoes Sneakers For Me...',
 'Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'casual for men (blue 06) Sneakers For Men',
 'Super Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...',
 'Sneakers For Men',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Sneakers For Men',
 'Fashionable casual sneakers shoes Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Unique & Perfect Collection Combo Pack of 02 Shoes for ...',
 'Fashionable casual sneaker shoes Sneakers For Men',
 'Fashionable casual sneakers shoes Sneakers For Men',
 'Modern & Trendy Collection Combo Pack of 02 Shoes for M...',
 'Speed Set of 5 Pairs Sneakers Outdoors Casuals for Men ...',
 'Fashionable shoes for men Sneakers For Men',
 'Sneakers for men(black_6) Sneakers For Men',
 'Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For ...',
 '494 Perfect Sports Shoes for Running Training Hikking &...',
 'Casual Sneakers Shoes For Men Sneakers For Men Sneakers...',
 'Sneakers For Men',
 'Black Sneaker For Men Sneakers For Men',
 "Modern Fashion Shoes Men's Causal Sneaker,Black SUP, Wa...",
 'Series 7 Sneakers For Men',
 'Perfect & Affordable Combo Pack of 03 Pairs Casual Snea...',
 'HAWK21 Sneakers For Men',
 'Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Sneakers For Men',
 'Trend Sneakers For Men',
 'Men 5014 Latest Collection Stylish Casual Sports Loafer...',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'casual for men (black 08) Sneakers For Men',
 'Sneakers For Men',
 'Men Boxer Sneakers For Men',
 'Combo Pack of 4 Casual Shoes Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Men White Sneakers Sneakers For Men',
 "Casual shoes,Sneakers for men's,shoes for men's Sneaker...",
 'Rockstyle Trending Multicolor Ultralight canvas Sport/ ...',
 'SM-322 Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Sneakers For Men',
 'Luxury Fashionable casual sneaker shoes Sneakers For Me...',
 'Perfect & Affordable Combo Pack of 02 Pairs Sneakers Ou...',
 'Synthetic Leather Casual Partywear Wedding Sneakers Sho...',
 'Latest Collection-1227 Stylish Casual Sports Sneakers F...',
 'Fashionable casual sneaker shoes Sneakers For Men',
 'Combo Pack of 4 Latest Collection Stylish Casual Loafer...',
 'White Sneaker For Men Sneakers For Men',
 'Fashionable casual sneaker shoes Sneakers For Men',
 'Casual Sneakers Shoes For Men Sneakers For Men',
 'White Sneakers Sneakers For Men',
 'SM-162 Sneakers For Men',
 'Fashionable shoes for men Sneakers For Men',
 'Sneakers For Men',
 'Super 445 Fashion Sneakers For Men',
 'Casual Sneakers Shoes For Men Sneakers For Men Sneakers...',
 "Modern Fashion Shoes Men's Causal Sneaker,Black SUP, Wa...",
 'Sneakers For Men',
 'Casual Sneakers White Shoes For Men Sneakers For Men',
 'Luxury Fashionable casual sneaker shoes Sneakers For Me...',
 'Sneakers For Men',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Sneakers For Men',
 'Sneakers For Men',
 'Kor Sneakers For Men',
 'SM-322 Sneakers For Men',
 'Sneakers For Men',
 'Unique & Perfect Collection Combo Pack of 02 Shoes for ...',
 'Chevit Latest Fashion Combo Pack of 2 Pairs Casual Outd...',
 'Sneakers For Men',
 'Sneakers For Men',
 'Perfect & Affordable Combo Pack of 02 Pairs Sneakers Ou...',
 'Poise Perf V1 IDP Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Luxury Fashionable casual sneaker shoes Sneakers For Me...',
 'Fashionable casual sneaker shoes Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Puma Rebound LayUp SL Sneakers For Men',
 'Fashionable casual sneaker shoes Sneakers For Men',
 'Puma Rebound LayUp SL Sneakers For Men',
 'MESTO Sneakers For Men',
 'Casual Sneakers Shoes For Men Sneakers For Men Sneakers...',
 'Sneakers For Men',
 'Affordable Combo Pack of 03 Pairs Sneakers Outdoor Loaf...',
 "Modern Fashion Shoes Men's Causal Sneaker,Black SUP, Wa...",
 'Casual Sneakers Sneakers For Men',
 'Casual Sneakers White Shoes For Men And Boys Sneakers F...',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Wh...",
 'HAWK21 Sneakers For Men',
 'Sneakers For Men',
 'Simha IDP Sneakers For Men',
 'Skypy-31 Walking Shoes,Training Shoes,Sneakers,Loafers,...',
 'Sneakers For Men']

In [82]:
# Price

for i in url_pages[:3]:
    driver.get(i)
    pri = driver.find_elements_by_xpath('//div[@class="_30jeq3"]')
    for i in pri:
        price.append(i.text)
    
price

['₹399',
 '₹299',
 '₹378',
 '₹499',
 '₹240',
 '₹474',
 '₹599',
 '₹404',
 '₹426',
 '₹349',
 '₹377',
 '₹399',
 '₹424',
 '₹299',
 '₹449',
 '₹399',
 '₹404',
 '₹499',
 '₹683',
 '₹449',
 '₹474',
 '₹474',
 '₹284',
 '₹499',
 '₹499',
 '₹407',
 '₹426',
 '₹369',
 '₹499',
 '₹297',
 '₹664',
 '₹599',
 '₹299',
 '₹398',
 '₹499',
 '₹499',
 '₹748',
 '₹445',
 '₹240',
 '₹249',
 '₹418',
 '₹499',
 '₹474',
 '₹399',
 '₹260',
 '₹698',
 '₹359',
 '₹299',
 '₹625',
 '₹379',
 '₹429',
 '₹404',
 '₹817',
 '₹474',
 '₹499',
 '₹399',
 '₹473',
 '₹358',
 '₹240',
 '₹369',
 '₹499',
 '₹407',
 '₹398',
 '₹399',
 '₹399',
 '₹348',
 '₹730',
 '₹399',
 '₹469',
 '₹499',
 '₹350',
 '₹449',
 '₹379',
 '₹398',
 '₹555',
 '₹499',
 '₹299',
 '₹499',
 '₹444',
 '₹369',
 '₹449',
 '₹378',
 '₹279',
 '₹299',
 '₹579',
 '₹1,920',
 '₹790',
 '₹399',
 '₹470',
 '₹649',
 '₹407',
 '₹399',
 '₹979',
 '₹599',
 '₹1,653',
 '₹399',
 '₹283',
 '₹199',
 '₹399',
 '₹449',
 '₹512',
 '₹579',
 '₹2,517',
 '₹499',
 '₹674',
 '₹2,443',
 '₹1,047',
 '₹369',
 '₹680',
 '₹426',
 '₹664',
 '₹599',
 '₹995',
 '₹499',
 '₹384',
 '₹499',
 '₹398',
 '₹1,310',
 '₹599',
 '₹424']

In [83]:
# Discount

for i in url_pages[:3]:
    driver.get(i)
    disc = driver.find_elements_by_xpath('//div[@class="_3Ay6Sb"]')
    for i in disc:
        discount.append(i.text)
    
discount

['85% off',
 '86% off',
 '62% off',
 '75% off',
 '51% off',
 '52% off',
 '62% off',
 '60% off',
 '78% off',
 '65% off',
 '62% off',
 '55% off',
 '57% off',
 '70% off',
 '70% off',
 '50% off',
 '86% off',
 '80% off',
 '72% off',
 '71% off',
 '52% off',
 '86% off',
 '71% off',
 '69% off',
 '50% off',
 '68% off',
 '67% off',
 '40% off',
 '50% off',
 '77% off',
 '74% off',
 '75% off',
 '70% off',
 '60% off',
 '50% off',
 '75% off',
 '62% off',
 '55% off',
 '51% off',
 '2% off',
 '71% off',
 '50% off',
 '52% off',
 '80% off',
 '47% off',
 '65% off',
 '80% off',
 '85% off',
 '16% off',
 '62% off',
 '66% off',
 '86% off',
 '18% off',
 '40% off',
 '50% off',
 '60% off',
 '73% off',
 '64% off',
 '51% off',
 '78% off',
 '81% off',
 '68% off',
 '69% off',
 '50% off',
 '60% off',
 '65% off',
 '23% off',
 '71% off',
 '53% off',
 '50% off',
 '29% off',
 '69% off',
 '62% off',
 '69% off',
 '44% off',
 '40% off',
 '70% off',
 '50% off',
 '79% off',
 '75% off',
 '55% off',
 '62% off',
 '72% off',
 '80% off',
 '42% off',
 '51% off',
 '20% off',
 '85% off',
 '70% off',
 '56% off',
 '59% off',
 '86% off',
 '27% off',
 '53% off',
 '58% off',
 '60% off',
 '43% off',
 '80% off',
 '69% off',
 '86% off',
 '67% off',
 '42% off',
 '49% off',
 '78% off',
 '32% off',
 '51% off',
 '61% off',
 '80% off',
 '31% off',
 '78% off',
 '71% off',
 '50% off',
 '23% off',
 '50% off',
 '61% off',
 '71% off',
 '60% off',
 '56% off',
 '25% off',
 '55% off']

In [84]:
First_100_sneakers = pd.DataFrame(index = list(range(1,101)))

First_100_sneakers["Brane"] = brand_name[:100]
First_100_sneakers["Product Description"] = product_description[:100]
First_100_sneakers["Price"] = price[:100]
First_100_sneakers["Discount"] = discount[:100]

First_100_sneakers

,Brane,Product Description,Price,Discount
1,aadi,Sneakers For Men,₹399,85% off
2,Xtoon,Luxury Fashionable casual sneaker shoes Sneake...,₹299,86% off
3,Numenzo,Sneakers For Men,₹378,62% off
4,ASTEROID,Original Luxury Branded Fashionable Men's Casu...,₹499,75% off
5,World Wear Footwear,5011-Latest Collection Stylish Casual Loafer S...,₹240,51% off
...,...,...,...,...
96,India hub,"Casual , Partywear Sneakers Shoes For Men's An...",₹399,60% off
97,HOTSTYLE,HAWK21 Sneakers For Men,₹283,43% off
98,REEBOOT,Sneakers For Men,₹199,80% off
99,luxury fashion,Simha IDP Sneakers For Men,₹399,69% off
100,STRANGER BROTHERS,"Skypy-31 Walking Shoes,Training Shoes,Sneakers...",₹449,86% off

### Q9: Go to the link - https://www.myntra.com/shoes Set Price filter to “Rs. 6649 to Rs. 13099” , Color filter to “Black” And then scrape First 100 shoes data you get. The data should include “Brand” of the shoes , Short Shoe description, price of the shoe

In [85]:
# Importing necessary Libraries

import selenium
from selenium import webdriver
import pandas as pd

In [86]:
# Let's first connect to the driver

driver = webdriver.Chrome("chromedriver.exe")
print(driver)

<selenium.webdriver.chrome.webdriver.WebDriver (session="8e2ba47bc4b337f8544ebcba21870c98")>

In [87]:
# Let's open the webpage where we have to scrape the data

url = 'https://www.myntra.com/shoes'
driver.get(url)

In [88]:
# Set Color filter to “Black”

color_filter = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[6]/ul/li[1]/label/div')
color_filter.click()

In [89]:
# Price filter range “Rs. 6649 to Rs. 13099” didn't find.
# So, I am going to set the Price filter to “Rs. 5387 to Rs. 10525”

price_filter = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[5]/ul/li[2]/label/div')
price_filter.click()

In [90]:
# Empty Lists

url_pages = []
brand_name = []
short_description = []
price = []

In [91]:
# Page links

url = driver.find_elements_by_xpath('//div[@class="results-showMoreContainer"]//a')
for i in url:
    url_pages.append(i.get_attribute("href"))

url_pages

['https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0&p=2',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0&p=3',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0&p=4',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0&p=5',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0&p=6',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0&p=7',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0&p=8',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0&p=9',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0&p=10',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A5387.0_10525.0_5387.0%20TO%2010525.0&p=2']

In [92]:
# Brand Names

for i in url_pages[:4]:
    driver.get(i)
    brand = driver.find_elements_by_xpath('//h3[@class="product-brand"]')
    for j in brand:
        brand_name.append(j.text)
brand_name

['ADIDAS',
 'UNDER ARMOUR',
 'Puma',
 'Puma',
 'UNDER ARMOUR',
 'Puma',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'RARE RABBIT',
 'Skechers',
 'Hush Puppies',
 'UNDER ARMOUR',
 'PUMA Hoops',
 'Quechua By Decathlon',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'RARE RABBIT',
 'Hush Puppies',
 'Hush Puppies',
 'Puma',
 'UNDER ARMOUR',
 'Bugatti',
 'FORCLAZ By Decathlon',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'Puma',
 'TARMAK By Decathlon',
 'Geox',
 'Hush Puppies',
 'Puma',
 'PUMA Motorsport',
 'UNDER ARMOUR',
 'Hush Puppies',
 'Quechua By Decathlon',
 'Geox',
 'Jack & Jones',
 'Geox',
 'Nike',
 'Puma',
 'Geox',
 'Nike',
 'J.FONTINI',
 'Puma',
 'Kenneth Cole',
 'DAVINCHI',
 'Hush Puppies',
 'ASICS',
 'Hush Puppies',
 'UNDER ARMOUR',
 'Geox',
 'FORCLAZ By Decathlon',
 'UNDER ARMOUR',
 'Hush Puppies',
 'Xtep',
 'PUMA Motorsport',
 'UNDER ARMOUR',
 'Ruosh',
 'Geox',
 'Puma',
 'Geox',
 'Kalenji By Decathlon',
 'J.FONTINI',
 'J.FONTINI',
 'Cole Haan',
 'Geox',
 'one8 Select BY VIRAT KOHLI',
 'Hush Puppies',
 'Bugatti',
 'Hush Puppies',
 'Bugatti',
 'Hush Puppies',
 'ADIDAS',
 'Hush Puppies',
 'Heel & Buckle London',
 'Geox',
 'Bugatti',
 'Xtep',
 'Geox',
 'PUMA Motorsport',
 'Alberto Torresi',
 'Ruosh',
 'Ruosh',
 'KIPRUN By Decathlon',
 'Geox',
 'Quechua By Decathlon',
 'J.FONTINI',
 'Heel & Buckle London',
 'Heel & Buckle London',
 'Geox',
 'Hush Puppies',
 'Ruosh',
 'Vanilla Moon',
 'Geox',
 'Geox',
 'RARE RABBIT',
 'Metro',
 'Geox',
 'Geox',
 'Geox',
 'PUMA Hoops',
 'Hush Puppies',
 'ADIDAS',
 'RARE RABBIT',
 'Geox',
 'Sergio Tacchini',
 'Xtep',
 'Xtep',
 'Geox',
 'UNDER ARMOUR',
 'Geox',
 'Cole Haan',
 'Geox',
 'Cole Haan',
 'Geox',
 'Geox',
 'Puma',
 'Geox',
 'Nike',
 'Puma',
 'Mochi',
 'VIONIC',
 'Kenneth Cole',
 'J.FONTINI',
 'J.FONTINI',
 'Nike',
 'PUMA Motorsport',
 'Nike',
 'MANGO',
 'Nike',
 'Nike',
 'Geox',
 'Nike',
 'Kenneth Cole',
 'Lacoste',
 'Louis Philippe',
 'Puma',
 'ALDO',
 'Cole Haan',
 'Cole Haan',
 'Metro',
 'San Frissco',
 'Nike',
 'Geox',
 'Geox',
 'Cole Haan',
 'Geox',
 'Geox',
 'Hush Puppies',
 'Clarks',
 'Cole Haan',
 'Geox',
 'Puma',
 'Heel & Buckle London',
 'Heel & Buckle London',
 'UNDER ARMOUR',
 'Geox',
 'H&M',
 'Geox',
 'Mochi',
 'dmodot',
 'Nike',
 'Ruosh',
 'PUMA Motorsport',
 'Geox',
 'Florsheim',
 'Florsheim',
 'Cole Haan',
 'Nike',
 'LYN',
 'Vanilla Moon',
 'Bugatti',
 'Birkenstock',
 'Vanilla Moon',
 'Vanilla Moon',
 'Birkenstock',
 'Vanilla Moon',
 'Vanilla Moon',
 'Kenneth Cole',
 'Bugatti',
 'Kenneth Cole',
 'Kenneth Cole',
 'Metro',
 'Kenneth Cole',
 'Vanilla Moon',
 'Vanilla Moon',
 'UNDER ARMOUR',
 'Puma',
 'Puma',
 'Hush Puppies',
 'Kenneth Cole',
 'J.FONTINI',
 'Vanilla Moon',
 'Vanilla Moon',
 'Geox',
 'J.FONTINI',
 'J.FONTINI']

In [102]:
# Prices

for i in url_pages[:4]:
    driver.get(i)
    pri = driver.find_elements_by_xpath('//span[@class="product-discountedPrice"]')
    for j in pri:
        price.append(j.text)
price

['Rs. 6079',
 'Rs. 7857',
 'Rs. 5399',
 'Rs. 6299',
 'Rs. 8449',
 'Rs. 8999',
 'Rs. 5599',
 'Rs. 8099',
 'Rs. 6299',
 'Rs. 5999',
 'Rs. 6749',
 'Rs. 5399',
 'Rs. 8121',
 'Rs. 9749',
 'Rs. 8099',
 'Rs. 7149',
 'Rs. 6209',
 'Rs. 5663',
 'Rs. 5399',
 'Rs. 5639',
 'Rs. 7199',
 'Rs. 8099',
 'Rs. 5849',
 'Rs. 8999',
 'Rs. 7199',
 'Rs. 10399',
 'Rs. 5399',
 'Rs. 9899',
 'Rs. 6999',
 'Rs. 6399',
 'Rs. 6299',
 'Rs. 6299',
 'Rs. 8999',
 'Rs. 5599',
 'Rs. 5599',
 'Rs. 5592',
 'Rs. 6399',
 'Rs. 5599',
 'Rs. 5999',
 'Rs. 9899',
 'Rs. 8094',
 'Rs. 7006',
 'Rs. 6299',
 'Rs. 5739',
 'Rs. 9449',
 'Rs. 7192',
 'Rs. 7192',
 'Rs. 5399',
 'Rs. 5394',
 'Rs. 8091',
 'Rs. 7699',
 'Rs. 9899',
 'Rs. 5999',
 'Rs. 9599',
 'Rs. 8799',
 'Rs. 5499',
 'Rs. 8771',
 'Rs. 7039',
 'Rs. 6013',
 'Rs. 8999',
 'Rs. 7413',
 'Rs. 5950',
 'Rs. 6229',
 'Rs. 8099',
 'Rs. 9599',
 'Rs. 8999',
 'Rs. 7199',
 'Rs. 6499',
 'Rs. 6747',
 'Rs. 5694',
 'Rs. 7499',
 'Rs. 7199',
 'Rs. 6749',
 'Rs. 6499',
 'Rs. 10341',
 'Rs. 7499',
 'Rs. 8394',
 'Rs. 7199',
 'Rs. 6392',
 'Rs. 6392',
 'Rs. 6749',
 'Rs. 7494',
 'Rs. 8999',
 'Rs. 5949',
 'Rs. 6293',
 'Rs. 6113',
 'Rs. 9513',
 'Rs. 5394',
 'Rs. 5391',
 'Rs. 5391',
 'Rs. 5599',
 'Rs. 6299',
 'Rs. 5803',
 'Rs. 5999',
 'Rs. 6079',
 'Rs. 9899',
 'Rs. 8999',
 'Rs. 5399',
 'Rs. 6299',
 'Rs. 8449',
 'Rs. 8999',
 'Rs. 5599',
 'Rs. 7199',
 'Rs. 6299',
 'Rs. 9899',
 'Rs. 5999',
 'Rs. 6749',
 'Rs. 5399',
 'Rs. 8121',
 'Rs. 9749',
 'Rs. 7149',
 'Rs. 5663',
 'Rs. 6209',
 'Rs. 6209',
 'Rs. 5639',
 'Rs. 8099',
 'Rs. 5849',
 'Rs. 7199',
 'Rs. 8999',
 'Rs. 6299',
 'Rs. 10399',
 'Rs. 5399',
 'Rs. 6999',
 'Rs. 6399',
 'Rs. 6299',
 'Rs. 6299',
 'Rs. 8999',
 'Rs. 5599',
 'Rs. 5599',
 'Rs. 5592',
 'Rs. 8099',
 'Rs. 6399',
 'Rs. 5599',
 'Rs. 5999',
 'Rs. 8094',
 'Rs. 8099',
 'Rs. 7006',
 'Rs. 5739',
 'Rs. 7192',
 'Rs. 7192',
 'Rs. 5399',
 'Rs. 5394',
 'Rs. 9899',
 'Rs. 8091',
 'Rs. 8091',
 'Rs. 6749',
 'Rs. 7699',
 'Rs. 8099',
 'Rs. 5999',
 'Rs. 9599',
 'Rs. 8799',
 'Rs. 5499',
 'Rs. 8771',
 'Rs. 7039',
 'Rs. 6299',
 'Rs. 6013',
 'Rs. 5599',
 'Rs. 7413',
 'Rs. 5950',
 'Rs. 6229',
 'Rs. 9599',
 'Rs. 6499',
 'Rs. 6747',
 'Rs. 5694',
 'Rs. 7499',
 'Rs. 5994',
 'Rs. 6499',
 'Rs. 10341',
 'Rs. 7499',
 'Rs. 8394',
 'Rs. 7199',
 'Rs. 8099',
 'Rs. 8999',
 'Rs. 6392',
 'Rs. 6392',
 'Rs. 6749',
 'Rs. 8999',
 'Rs. 7199',
 'Rs. 7494',
 'Rs. 7199',
 'Rs. 8999',
 'Rs. 5949',
 'Rs. 6293',
 'Rs. 6113',
 'Rs. 9513',
 'Rs. 5394',
 'Rs. 5391',
 'Rs. 5391',
 'Rs. 5599',
 'Rs. 5803',
 'Rs. 6299']

In [97]:
# Short Description

for i in url_pages[:4]:
    driver.get(i)
    description = driver.find_elements_by_xpath('//h4[@class="product-product"]')
    for j in description:
        short_description.append(j.text)
short_description

['Women Response SR Running',
 'Men Charged Bandit 6 Running',
 'Men Perforations Leather Brogues',
 'Axelion Block Running Shoes',
 'Men Charged Assert 8 Marble',
 'Men Cell Fraction Fade Running',
 'Men Charged Vantage Running',
 'Men Charged Pursuit 2 SE Shoes',
 'Unisex Project Rock Recruit',
 'Men Charged Commit 3 Training',
 'Men Charged Pursuit 2 SE',
 'Women Charged Vantage ClrShft',
 'Women UltraRide Running Shoes',
 'Men Solid Leather Formal Oxfords',
 'Men Equalizer 4.0 Trail',
 'Men Leather Driving Shoes',
 'Men HOVR Sonic STRT Tech Shoes',
 'Unisex Clyde Basketball Shoes',
 'Women Waterproof Hiking Shoes',
 'Men Victory Sneakers',
 'Women Leather Pumps',
 'GS SC 3Zero IV Basketball',
 'Men Leather Slip-On Sneakers',
 'Women Eternity Nitro Running',
 'Men Formal Derbys',
 'Men Phade Running Shoes',
 'Men Perforated Mule Sneakers',
 'TREKKING 100 Boots',
 'Women Charged Assert 8 Running',
 'Men Charged Rogue 2.5 RFLCT',
 'Men Leader VT Running Shoes',
 'Men Basketball Shoes',
 'Men Solid Leather Formal Slip-Ons',
 'Men Leather Formal Slip-Ons',
 'Men SOFTRIDE Rift Shoes',
 'Unisex Ferrari Sneakers',
 'Women Liquify Rebel Running',
 'Men Textured Leather Formal Derbys',
 'Men Leather Formal Brogues',
 'Men Trekking Shoes',
 'Men Leather Flat Boots',
 'Women AIR MAX VIVA Sneakers',
 'Riveted Leather Block Heels',
 'Women Deviate Nitro Running',
 'Men Leather Semiformal Driving',
 "Men BlazerLow '77 Sneakers",
 'Women Velocity Nitro Running',
 'Men Driving Shoes Casual Shoes',
 'Men Solid Leather Formal Brogues',
 'Women Running Shoes',
 'Women Charged Bandit 6 Running',
 'Men Leather Formal Oxfords',
 'Men Hiking Shoes',
 'Women Charged Rogue 2.5ClrSft',
 'Women Running Shoes',
 'Men Solid Leather Formal Slip-Ons',
 'Unisex Sneakers',
 'Women Charged Impulse Shft',
 'Men Formal Leather Brogues',
 'Women Leather Pumps',
 'Men Leather Formal Derbys',
 'Women BETTER FOAM Adore Shoes',
 'Men Driving Shoes',
 'Men Solid Sneakers',
 'Men Solid Loafers',
 'Men Wingtip Oxford Sneakers',
 'Men Textured Leather Driving Shoes',
 'Men Textured Leather Handcrafted Sole Wingman Formal Slip-Ons',
 'Riveted Leather Block Heels',
 'Men Sneakers',
 'Men Textured Leather Loafers',
 'Men Leather Slip-On Sneakers',
 'Men Sneakers',
 'Men Colourblocked Driving Shoes',
 'Men Solid Casual Sneakers',
 'Men KD500 Running Shoe',
 'Men Solid Leather Formal Slip-Ons',
 'Men Leather Formal Derbys',
 'Women Running Shoes',
 'Men Leather Derbys',
 'Women Leather Stilettos',
 'Men Slip-On Sneakers',
 'AIR MEGA Energy Ring Shoes',
 'SF Evo Cat Sock Lace LS',
 'Men Leather Formal Slip Ons',
 'Men Leather Formal Derbys',
 'Men Solid Leather Formal Oxfords',
 'Men Leather Formal Brogues',
 'Women Running Shoes',
 'Basketweave Block Heels',
 'Waterproof Walking Shoes',
 'Men Solid Formal Loafers',
 'Men Perforations Brogues',
 'Women Peep Toe Heels',
 'Women Leather Pumps',
 'Men Leather Monk Shoes',
 'Men Textured Derbys',
 'Women Solid Block Heels',
 'Men Solid Leather Sneakers',
 'Men Perforated Slip On Sneaker',
 'Women Leather Boat Shoes',
 'Women Sandals',
 'Women Solid Leather Loafers',
 'Men Solid Leather Sneakers',
 'Unisex Clyde Basketball Shoes',
 'Women Solid Leather Pumps',
 'Women Edge Lux 4 Running',
 'Men Leather Driving Shoes',
 'Men Perforated Slip On Sneaker',
 'Men Solid Sneakers',
 'Men Running Shoes',
 'Men Running Shoes',
 'Women Charged Rogue 2 Running',
 'Men GENERATION ZEROGRAND STITCHLITE',
 'Men Leather Slip-On Sneakers',
 'Leather Sneakers',
 'Men Leather Formal Derbys',
 'Men Solid Leather Formal Derbys',
 'Men 365 Evoknit Ignite Ct Football',
 'Men Leather Driving Shoes',
 'Women AIR ZOOM Running',
 'Men One 3 Lth FG Football',
 'Men Textured Sneakers',
 'Men Textured Sneakers',
 'Men Textured Leather Loafers',
 'Men Textured Leather Loafers',
 'Men AIR ZOOM PEGASUS 38 Run',
 'Unisex Mercedes Running Shoes',
 'Men ZOOM WINFLO 6 Running',
 'Men AIR ZOOM PEGASUS 38 Run',
 'Men JORDAN ONE TAKE II Shoes',
 'Men Leather Boots',
 'Men ZOOM WINFLO8 Running Shoes',
 'Men Solid Leather Sneakers',
 'Men Woven Design Slip-On Sneakers',
 'Men Leather Formal Slip-Ons',
 'Women Fraction Running Shoes',
 'Women Flatform Sneakers',
 'Women Solid Sneakers',
 'Women Open Toe Flats',
 'Men Solid Formal Leather Slip-On Shoes',
 'Women Sneakers',
 'Men Leather Loafers',
 'Men Air Zoom Structure Running',
 'Women Leather Block Heels',
 'Solid Leather Wedges',
 'Women Leather Heels',
 'Women Solid Wedges',
 'Women Leather Block Heels',
 'Sustainable Leather Pumps',
 'Men Leather Formal Derbys',
 'Men Leather Boots',
 'Women Woven Design Sneakers',
 'Women Flatform Sneakers',
 'Men Leather Formal Derbys',
 'Unisex KING Top FG Shoes',
 'Women Leather Pumps',
 'Women Block Heels',
 'Women Charged Breathe OIL SLK',
 'Men Leather Formal Oxfords',
 'Men Leather Formal Oxfords',
 'Men Solid Leather Formal Slip-Ons',
 'Black Leather boots',
 'Men Woven Design Leather Mules',
 'Men Crater Remixa Sneakers',
 'Men Leather Monk Shoes',
 'Men Solid Leather Formal Derbys',
 'Men BMW MMS Kart Cat Mid III',
 'Men Solid Leather Formal Loafers',
 'Women Woven Design Sneakers',
 'Men Renew Retaliation TR 3',
 'Embellished Platform Heels',
 'Women Sandals',
 'Women Solid Block Heels',
 'Women Block Heels',
 'Women Wedges',
 'Women Sydney Flats',
 'Women Gizeh Flats',
 'Women Leather Flatforms',
 'Women Leather Sneakers',
 'Women Leather Block Heels',
 'Men Solid Leather Formal Derbys',
 'Men Leather Formal Derbys',
 'Women Mules',
 'Women Solid Flat Boots',
 'Women Flatform Sneakers',
 'Women Leather Loafers',
 'Men Solid Leather Formal Slip-Ons',
 'Men Solid Leather Formal Derbys',
 'Women Wedges',
 'Women Heels',
 'Unisex GS Assert 8 UFM SYN',
 'Unisex Ralph Sampson Sneakers',
 'Men Ultra Triller FM Shoes',
 'Men Solid Leather Formal Oxfords',
 'Men Leather Formal Loafers',
 'Women Open Toe Flats',
 'Women Leather Horsebit Loafers',
 'Women Open Toe Flats',
 'Men Leather Formal Loafers']

In [103]:
First_100_shoes = pd.DataFrame(index = list(range(1,101)))

First_100_shoes["Brand Name"] = brand_name[:100]
First_100_shoes["Product Description"] = short_description[:100]
First_100_shoes["Price"] = price[:100]

First_100_shoes

       Brand Name               Product Description     Price
1          ADIDAS         Women Response SR Running  Rs. 6079
2    UNDER ARMOUR      Men Charged Bandit 6 Running  Rs. 7857
3            Puma  Men Perforations Leather Brogues  Rs. 5399
4            Puma       Axelion Block Running Shoes  Rs. 6299
5    UNDER ARMOUR       Men Charged Assert 8 Marble  Rs. 8449
..            ...                               ...       ...
96   Vanilla Moon            Men Leather Monk Shoes  Rs. 9899
97           Geox               Men Textured Derbys  Rs. 8999
98           Geox           Women Solid Block Heels  Rs. 5399
99    RARE RABBIT        Men Solid Leather Sneakers  Rs. 6299
100         Metro    Men Perforated Slip On Sneaker  Rs. 8449

[100 rows x 3 columns]

### Q10: Go to webpage https://www.amazon.in/ Enter “Laptop” in the search field and then click the search icon. Then set CPU Type filter to “Intel Core i7” and “Intel Core i9”. After setting the filters scrape first 10 laptops data. You have to scrape 3 attributes for each laptop:
1. Title
2. Ratings
3. Price

In [104]:
# Importing necessary Libraries

import selenium
from selenium import webdriver
import pandas as pd

In [105]:
# Let's first connect to the driver

driver = webdriver.Chrome("chromedriver.exe")
print(driver)

<selenium.webdriver.chrome.webdriver.WebDriver (session="1014531665dba076988f59d47d4132c4")>

In [106]:
# Let's open the webpage where we have to scrape the data

url = 'https://www.amazon.in/'
driver.get(url)

In [107]:
# Enter 'Laptop' in the search bar

laptop = driver.find_element_by_xpath('//input[@type="text"]')
laptop.send_keys("Laptop")

In [108]:
# Click on the search icon

click = driver.find_element_by_xpath('//input[@id="nav-search-submit-button"]')
click.click()

In [109]:
# Set CPU Type filter to “Intel Core i7”

i7_filter = driver.find_element_by_xpath('/html/body/div[1]/div[2]/div[1]/div/div[2]/div/div[3]/span/div[1]/span/div/div/div[6]/ul[1]/li[26]/span/a/div/label/i')
i7_filter.click()

In [110]:
# Set CPU Type filter to “Intel Core i9”

i9_filter = driver.find_element_by_xpath('/html/body/div[1]/div[2]/div[1]/div/div[2]/div/div[3]/span/div[1]/span/div/div/div[6]/ul[1]/li[28]/span/a/div/label/i')
i9_filter.click()

In [111]:
# Empty Lists

title_name = []
ratings = []
price = []

In [112]:
# Titles

title = driver.find_elements_by_xpath('//h2[@class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"]')
for i in title:
    title_name.append(i.text)
    
title_name

['MSI GF65 Thin, Intel i7-10750H, 15.6" FHD (39.6 cm) IPS-Level 144Hz Panel Laptop (16GB/512GB NVMe SSD/Windows 10 Home/Nvidia GTX1660 Ti 6GB GDDR6/Black/1.86Kg), 10SDR-1280IN',
 'ASUS TUF Dash F15 (2021), 15.6" (39.62 cms) FHD 144Hz, Intel Core i7-11370H 11th Gen, RTX 3050 Ti 4GB Graphics, Gaming Laptop (16GB/1TB SSD/Office 2019/Windows 10/Eclipse Gray/2 kg), FX516PE-HN088TS',
 'HP Pavilion (2021) Thin & Light 11th Gen Core i7 Laptop, 16 GB RAM, 1TB SSD, Iris Xe Graphics, 14" (35.56cms) FHD Screen, Windows 10, MS Office, Backlit Keyboard (14-dv0058TU)',
 'MSI GF65 Thin, Intel i7-10750H, 15.6" FHD (39.6 cm) IPS-Level 144Hz Panel Laptop (16GB/512GB NVMe SSD/Windows 10 Home/Nvidia GTX1660 Ti 6GB GDDR6/Black/1.86Kg), 10SDR-1280IN',
 'Life Digital Laptop 15.6-inch (39.62 cms) (Intel Core i7, 4GB RAM, 256GB SSD, Windows 10), ZED AIR CX7',
 'Life Digital Laptop 15.6-inch (39.62 cms) (Intel Core i7, 8GB RAM, 512GB SSD, Windows 10), ZED AIR CX7',
 'HP Pavilion Gaming 10th Gen Intel Core i7 Processor 15.6-inch FHD Gaming Laptop (16GB/512GB SSD + 32GB Intel Optane/Windows 10/NVIDIA 1650Ti 4GB/Shadow Black), 15-dk1509TX',
 'HP Pavilion x360 (2021) 14" (35.56cms) FHD Touchscreen Laptop, 11th Gen Core i7, 8 GB RAM, 512GB SSD, 2-in-1 Convertible, Windows 10, MS Office, Finger Print Reader (14-dw1040TU)',
 'Fujitsu UH-X 11th Gen Intel Core i7 13.3” (33.78cm) FHD IPS 400Nits 2-in1 Touch Convertible Laptop (16GB/1TB SSD/Win10/Office/Iris Xe Graphics/Backlit Kb/Black/997gms), 4ZR1D71993',
 'Lenovo IdeaPad Flex 5 11th Gen Intel Core i7 14"(35.56cm) FHD IPS 2-in-1 Touchscreen Laptop(16GB/512GB SSD/Windows 10/MS Office/Lenovo Digital Pen/Fingerprint Reader/Graphite Grey/1.5Kg), 82HS0092IN',
 'ASUS TUF Gaming F15 (2020), 15.6-inch (39.62 cms) FHD 144Hz, Intel Core i7-10870H 10th Gen, NVIDIA GeForce GTX 1650 4GB Graphics, Gaming Laptop(8GB/512GB SSDWindows 10/Gray/2.3 Kg), FX566LH-HN255T',
 'Dell 14 (2021) i7-1165G7 2in1 Touch Screen Laptop, 16Gb RAM, 512Gb SSD, 14” (35.56 cms) FHD Display, Win 10 + MSO, Backlit KB + FPR + Active Pen, Silver Metal Color (Inspiron 5410, D560469WIN9S)',
 'Mi Notebook Horizon Edition 14 Intel Core i7-10510U 10th Gen 14-inch (35.56 cms) Thin and Light Laptop(8GB/512GB SSD/Windows 10/Nvidia MX350 2GB Graphics/Grey/1.35Kg), XMA1904-AF+Webcam',
 '(Renewed) Life Digital Laptop 15.6-inch (39.62 cms) (Intel Core i7, 8GB RAM, 512GB SSD, Windows 10), ZED AIR CX7',
 'Lenovo Yoga 7 11th Gen Intel Core i7-1165G7 14" (35.56cm) FHD IPS 2-in-1 Touchscreen Laptop (16GB/512GB SSD/Windows 10/MS Office/Lenovo Digital Pen/Fingerprint Reader/Slate Grey/1.43Kg), 82BH004HIN',
 'MSI GF63 Thin, Intel 10th Gen. i7-10750H, 15.6" FHD Gaming Laptop (8GB/512 GB NVMe SSD/Windows 10 Home/Nvidia GTX 1650 Ti Max-Q/Black/1.8Kg), 10SCSR-660IN',
 '(Renewed) Lenovo Intel Core i7-4th Gen 14 Inch(35.56 cms) 1920 x 1080 HD Laptop (8GB RAM/128GB SSD & 1TB HDD/Windows 10 Pro/MS Office/ Intel HD graphics,Black,2.0kg) Lenovo ThinkPad T440p',
 '(Renewed) Lenovo Intel Core i7-4th Gen 14 Inch(35.56 cms) 1920 x 1080 HD Laptop (16GB RAM /1TB SSD/Windows 10 Pro/MS Office/ Intel HD graphics,Black,2.0kg) Lenovo ThinkPad T440p',
 '(Renewed) Lenovo Intel Core i7-4th Gen 14 Inch(35.56 cms) 1920 x 1080 HD Laptop (8GB RAM/500GB HDD/Windows 10 Pro/MS Office/ Intel HD graphics,Black,2.0kg) Lenovo ThinkPad T440p',
 'OMEN 17 Gaming Laptop, NVIDIA GeForce RTX 2070, Intel Core i7-10750H, 16 GB DDR4 RAM, 512 GB PCIe NVMe SSD, 17.3" 144Hz Full HD, Windows 10 Home, RGB Keyboard (17-cb1080nr, 2020 Model)',
 'NEXSTGO Primus NX201 NP15N1IN008P 15.6-inch Laptop (Core i7-8550U/8GB/256GBSSD/Windows 10 Pro/Full HD + IR/Finger Print/Integrated Graphics/Thin & Light/1.88KG), Dark Gray',
 '(Renewed) Lenovo T430 14-inch Laptop (Core i7/ 8GB RAM(Upgradable to 16)/512GB SSD/Windows 10 Pro/MS Office 2019, Intel Integrated Graphics, PAN INDIA WARRANTY) Black',
 'ASUS ROG Strix G G731GT 17.3" FHD Gaming Laptop GTX 1650 4GB Graphics (Core i7-9750H 9th Gen/16GB RAM/1TB PCIe SSD/Windows 10/Black/2.85 Kg), G731GT-AU059T',
 '(Renewed) Lenovo Legion Y740 Intel 9th Gen Core i7 15.6-Inch (39.62 cms) 1920 x 1080 (Full HD) Laptop (16 GB/1TB SSD/Windows 10 Home/MS Office /NVIDIA GeForce RTX 2060/Black/2.2 Kg), 81UH006YIN',
 'Lenovo ThinkPad P53s Workstation Laptop (Intel i7-8565U 4-Core, 24GB RAM, 1TB PCIe SSD, Quadro P520, 15.6" Full HD (1920x1080), Fingerprint, WiFi, Bluetooth, Webcam, Win 10 Pro) with USB3.0 Hub',
 '(Renewed) HP Intel Core i7 6700HQ 15.6-Inch (39.62 cms) 1920 X 1080 Laptop (8 GB/2 TB SSD/Windows/Intel HD Graphics & Nvidia 1000m/Grey/2.7 Kg), Zbook 15',
 'HP 14 Thin & Light 14" (35.56cms) FHD Laptop (11th Gen Intel i7-1165G7/8GB/512GB SSD/Windows 10/MS Office 2019/Alexa Built-in/Pale Gold/1.47 kg), 14s-dr2007TU',
 'Dell Alienware m15(R3) 15.6-inch FHD Gaming Laptop (10th Gen Core i7-10750H/16GB/512GB SSD/Windows 10 Home & MS Office/6GB NVIDIA GTX 1660 Ti Graphics), Lunar Light',
 'Acer Swift 5 14" (35.56cms) Full HD IPS Display with Touchscreen Ultra Thin and Light Notebook (Intel i7 - 11th Gen/16GB RAM/1TB SSD/Win10/Intel Iris Xe Graphics/1.05 Kg/Mist Green), SF514-55TA',
 'HP Envy 11th Gen Core i7 Processor 13.3-inch (33.78 cms) FHD Touchscreen Laptop (16GB/1TB SSD/Win 10/NVIDIA MX450 2GB/Natural Silver/1.3 kg), 13-ba1018TX']

In [113]:
# Ratings

# Ratings inspects is not working.....

In [114]:
# Price

pri = driver.find_elements_by_xpath('//span[@class="a-price-whole"]')
for i in pri:
    price.append(i.text)

price

['81,990',
 '1,07,990',
 '84,990',
 '81,990',
 '34,990',
 '39,990',
 '86,990',
 '81,999',
 '1,07,990',
 '88,990',
 '80,990',
 '85,490',
 '59,999',
 '35,990',
 '96,588',
 '1,00,990',
 '46,999',
 '50,999',
 '42,999',
 '56,155',
 '46,999',
 '99,990',
 '1,19,990',
 '77,990',
 '85,000',
 '1,74,990',
 '94,865',
 '1,09,990']

In [115]:
First_100_Laptops = pd.DataFrame(index = list(range(1,11)))

First_100_Laptops["Title"] = title_name[:10]
First_100_Laptops["Price"] = price[:10]

First_100_Laptops

                                                Title     Price
1   MSI GF65 Thin, Intel i7-10750H, 15.6" FHD (39....    81,990
2   ASUS TUF Dash F15 (2021), 15.6" (39.62 cms) FH...  1,07,990
3   HP Pavilion (2021) Thin & Light 11th Gen Core ...    84,990
4   MSI GF65 Thin, Intel i7-10750H, 15.6" FHD (39....    81,990
5   Life Digital Laptop 15.6-inch (39.62 cms) (Int...    34,990
6   Life Digital Laptop 15.6-inch (39.62 cms) (Int...    39,990
7   HP Pavilion Gaming 10th Gen Intel Core i7 Proc...    86,990
8   HP Pavilion x360 (2021) 14" (35.56cms) FHD Tou...    81,999
9   Fujitsu UH-X 11th Gen Intel Core i7 13.3” (33....  1,07,990
10  Lenovo IdeaPad Flex 5 11th Gen Intel Core i7 1...    88,990